<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;

class ElectronicsAndStationerySeeder extends Seeder
{
    public function run(): void
    {
        // 1. Electronics Categories
        $elecCategories = [
            [
                'name' => 'রিডিং লাইট ও ল্যাম্প',
                'slug' => 'reading-lights',
                'type' => 'electronics',
                'description' => 'চোখের সুরক্ষায় রিচার্জেবল ও ফ্লেক্সিবল রিডিং ল্যাম্প',
                'icon' => 'fas fa-lightbulb',
                'sort_order' => 1,
            ],
            [
                'name' => 'স্মার্ট স্টাডি ডিভাইস',
                'slug' => 'smart-study-devices',
                'type' => 'electronics',
                'description' => 'ডিজিটাল নোটপ্যাড, স্মার্ট পেন ও টাইমার ডিভাইস',
                'icon' => 'fas fa-tablet-alt',
                'sort_order' => 2,
            ],
            [
                'name' => 'অডিও ও হেডফোন',
                'slug' => 'audio-headphones',
                'type' => 'electronics',
                'description' => 'নয়েজ ক্যানসেলিং হেডফোন ও অডিওবুক প্লেয়ার',
                'icon' => 'fas fa-headphones',
                'sort_order' => 3,
            ],
            [
                'name' => 'পাওয়ার ও চার্জার',
                'slug' => 'power-chargers',
                'type' => 'electronics',
                'description' => 'ফাস্ট চার্জিং পাওয়ার ব্যাংক ও অ্যাডাপ্টার',
                'icon' => 'fas fa-bolt',
                'sort_order' => 4,
            ],
            [
                'name' => 'ডেস্ক গ্যাজেটস',
                'slug' => 'desk-gadgets',
                'type' => 'electronics',
                'description' => 'ডিজিটাল ক্লক, মিনি ফ্যান ও ক্লিন ক্লিনার',
                'icon' => 'fas fa-microchip',
                'sort_order' => 5,
            ],
        ];

        $elecCatModels = [];
        foreach ($elecCategories as $cat) {
            $elecCatModels[$cat['slug']] = ProductCategory::updateOrCreate(
                ['slug' => $cat['slug']],
                $cat
            );
        }

        // 2. Stationery Categories
        $statCategories = [
            [
                'name' => 'প্রিমিয়াম ডায়েরি ও নোটবুক',
                'slug' => 'diaries-notebooks',
                'type' => 'stationery',
                'description' => 'লেদার বাউন্ড ও হার্ডকভার এক্সিকিউটিভ ডায়েরি',
                'icon' => 'fas fa-book-open',
                'sort_order' => 1,
            ],
            [
                'name' => 'ফাউন্টেন পেন ও ক্যালিগ্রাফি',
                'slug' => 'pens-calligraphy',
                'type' => 'stationery',
                'description' => 'লাক্সারি কালির কলম, ব্রাশ পেন ও ক্যালিগ্রাফি কিট',
                'icon' => 'fas fa-pen-fancy',
                'sort_order' => 2,
            ],
            [
                'name' => 'আর্ট ও স্কেচবুক',
                'slug' => 'art-sketchbooks',
                'type' => 'stationery',
                'description' => 'ওয়াটারকালার প্যাড, ড্রয়িং পেন্সিল ও ক্যানভাস',
                'icon' => 'fas fa-palette',
                'sort_order' => 3,
            ],
            [
                'name' => 'বুকমার্ক ও রিডিং এক্সেসরিজ',
                'slug' => 'bookmarks-accessories',
                'type' => 'stationery',
                'description' => 'মেটাল বুকমার্ক, ম্যাগনিফায়ার ও পেজ হোল্ডার',
                'icon' => 'fas fa-bookmark',
                'sort_order' => 4,
            ],
            [
                'name' => 'অর্গানাইজার ও স্টোরেজ',
                'slug' => 'organizers-storage',
                'type' => 'stationery',
                'description' => 'ডেস্ক পেন স্ট্যান্ড, ডকুমেন্ট ফাইল ও ক্যাডি',
                'icon' => 'fas fa-folder-open',
                'sort_order' => 5,
            ],
        ];

        $statCatModels = [];
        foreach ($statCategories as $cat) {
            $statCatModels[$cat['slug']] = ProductCategory::updateOrCreate(
                ['slug' => $cat['slug']],
                $cat
            );
        }

        // 3. Electronics Products
        $electronicsProducts = [
            [
                'title' => 'আইডিয়া প্রো ফ্লেক্সিবল রিচার্জেবল রিডিং ল্যাম্প',
                'slug' => 'idea-pro-flexible-rechargeable-reading-lamp',
                'type' => 'electronics',
                'category_id' => $elecCatModels['reading-lights']->id,
                'brand' => 'Baseus',
                'model' => 'Comfort Pro Eye-Care',
                'sku' => 'ELC-LMP-01',
                'summary' => 'চোখের সুরক্ষায় ৩ রঙের আলোর মোড এবং টাচ কন্ট্রোল সুবিধা সম্বলিত এলইডি ক্লিপ-অন রিডিং ল্যাম্প।',
                'description' => 'দীর্ঘ সময় বই পড়ার জন্য উপযুক্ত ফ্লেক্সিবল এলইডি ল্যাম্প। এটি চোখের ওপর বাড়তি চাপ পড়তে দেয় না। ৩৬০ ডিগ্রি সহজে ঘোরানো যায় এবং ক্লিপের সাহায্যে টেবিল বা বইয়ের মলাটে সহজে আটকানো যায়। ১৮০০ মিলিঅ্যাম্পিয়ার ব্যাটারি একবার চার্জে প্রায় ১২ ঘন্টা নিরবচ্ছিন্ন আলো দেয়।',
                'price' => 1250,
                'discount_price' => 950,
                'stock' => 45,
                'warranty' => '৬ মাসের অফিসিয়াল রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.9,
                'reviews_count' => 38,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি ক্যাপাসিটি' => '1800mAh Li-ion',
                    'চার্জিং পোর্ট' => 'Type-C Fast Charging',
                    'কালার মোড' => 'Warm, Natural, Cool White',
                    'ব্রাইটনেস লেভেল' => '৩টি স্টেপ টাচ অ্যাডজাস্টেবল',
                    'বডি মেটেরিয়াল' => 'ABS + Flexible Silicone',
                ],
            ],
            [
                'title' => 'স্মার্ট ডিজিটাল এলসিডি রাইটিং প্যাড ও নোটবুক ১২ ইঞ্চি',
                'slug' => 'smart-digital-lcd-writing-pad-12-inch',
                'type' => 'electronics',
                'category_id' => $elecCatModels['smart-study-devices']->id,
                'brand' => 'Xiaomi',
                'model' => 'Mijia LCD Blackboard 12"',
                'sku' => 'ELC-NTP-02',
                'summary' => 'কাগজ ছাড়া নোট নেওয়া, অঙ্ক কষা ও ড্রয়িংয়ের জন্য আধুনিক চোখের সুরক্ষাযুক্ত ডিজিটাল প্যাড।',
                'description' => 'কাগজের অপচয় রোধ করতে স্টাডি ও অফিসের জন্য অত্যন্ত উপযোগী ১২ ইঞ্চি ডিজিটাল এলসিডি রাইটিং ট্যাবলেট। এতে রয়েছে ওয়ান-ক্লিক ক্লিয়ার বাটন এবং স্ক্রিন লক সুইচ যেন গুরুত্বপূর্ণ ড্রয়িং বা নোট মুছে না যায়।',
                'price' => 1650,
                'discount_price' => 1350,
                'stock' => 30,
                'warranty' => '১ বছরের ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 52,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'স্ক্রিন সাইজ' => '১২ ইঞ্চি প্রেসার সেনসিটিভ এলসিডি',
                    'ব্যাটারি' => 'CR2025 বাটন সেল (১ বছর ব্যাকআপ)',
                    'পেন স্টাইলাস' => 'ম্যাগনেটিক আল্ট্রা-লাইট পেন অন্তর্ভুক্ত',
                    'ওজন' => '২১৫ গ্রাম',
                ],
            ],
            [
                'title' => 'অ্যানকার সাউন্ডকোর অ্যাক্টিভ নয়েজ ক্যানসেলিং হেডফোন',
                'slug' => 'anker-soundcore-life-q30-anc-headphone',
                'type' => 'electronics',
                'category_id' => $elecCatModels['audio-headphones']->id,
                'brand' => 'Anker',
                'model' => 'Soundcore Life Q30',
                'sku' => 'ELC-HDP-03',
                'summary' => 'পড়াশোনায় পূর্ণ মনোযোগ ও অডিওবুক শোনার জন্য হাই-রেজ অডিও ও এআই হাইব্রিড নয়েজ ক্যানসলেশন।',
                'description' => 'পারিপার্শ্বিক সকল আওয়াজ ব্লক করে পড়ালেখা ও গবেষণায় শতভাগ মনোযোগ ধরে রাখতে অনবদ্য হাইব্রিড অ্যাক্টিভ নয়েজ ক্যানসেলিং হেডফোন। ৪০ ঘন্টা প্লে-টাইম এবং নরম মেমরি ফোম ইয়ারপ্যাড দীর্ঘ সময় আরামদায়ক ব্যবহার নিশ্চিত করে।',
                'price' => 8500,
                'discount_price' => 7490,
                'stock' => 18,
                'warranty' => '১৮ মাসের অফিশিয়াল ওয়ারেন্টি',
                'badge' => 'প্রিমিয়াম',
                'rating' => 4.95,
                'reviews_count' => 64,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'কানেক্টিভিটি' => 'Bluetooth 5.0 + AUX 3.5mm',
                    'ব্যাটারি ব্যাকআপ' => '৪০ ঘন্টা (ANC অন), ৬০ ঘন্টা (ANC অফ)',
                    'চার্জিং' => 'USB-C ফাস্ট চার্জিং (৫ মিনিটে ৪ ঘন্টা প্লেব্যাক)',
                    'অডিও কোডেক' => 'Hi-Res Audio Certified, AAC, SBC',
                ],
            ],
            [
                'title' => 'বেসাস পোর্টেবল ২০,০০০ এমএএইচ ফাস্ট চার্জিং পাওয়ার ব্যাংক',
                'slug' => 'baseus-portable-20000mah-fast-charging-power-bank',
                'type' => 'electronics',
                'category_id' => $elecCatModels['power-chargers']->id,
                'brand' => 'Baseus',
                'model' => 'Blade 22.5W Digital Display',
                'sku' => 'ELC-PWR-04',
                'summary' => 'এলইডি ডিজিটাল ডিসপ্লে ও মাল্টি-পোর্ট ২২.৫ ওয়াট আল্ট্রা-স্লিম পোর্টেবল পাওয়ার ব্যাংক।',
                'description' => 'ল্যাপটপ, ট্যাবলেট বা স্মার্টফোনের চার্জিং নিয়ে আর চিন্তা নেই। আধুনিক ব্যাটারি সুরক্ষাযুক্ত সলিড অ্যালুমিনিয়াম বডির প্রিমিয়াম পাওয়ার ব্যাংক। এক সাথে ৩টি ডিভাইস চার্জ দেওয়া সম্ভব।',
                'price' => 3200,
                'discount_price' => 2650,
                'stock' => 25,
                'warranty' => '১ বছরের ওয়ারেন্টি',
                'badge' => 'সেরা অফার',
                'rating' => 4.85,
                'reviews_count' => 29,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '20,000mAh / 3.7V (74Wh)',
                    'সর্বোচ্চ আউটপুট' => '22.5W Quick Charge 3.0 & PD 3.0',
                    'পোর্ট' => '২টি USB-A, ১টি Type-C ইন/আউট',
                    'ডিসপ্লে' => 'স্মার্ট ডিজিটাল পার্সেন্টেজ ডিসপ্লে',
                ],
            ],
            [
                'title' => 'স্মার্ট পমোডোরো স্টাডি টাইমার ও অ্যালার্ম ক্লক',
                'slug' => 'smart-pomodoro-study-timer-alarm-clock',
                'type' => 'electronics',
                'category_id' => $elecCatModels['desk-gadgets']->id,
                'brand' => 'Idea Smart',
                'model' => 'Cube Focus Timer Pro',
                'sku' => 'ELC-TMR-05',
                'summary' => 'পড়ার টেবিলে মনোযোগ ধরে রাখার জন্য কিউব রোটেশনাল পমোডোরো টাইমার ও সাইলেন্ট কাউন্টডাউন।',
                'description' => 'পমোডোরো টেকনিক অনুযায়ী পড়ালেখা বা কাজের সময়কে ২৫ মিনিট ফোকাস ও ৫ মিনিট ব্রেকে ভাগ করার জন্য আদর্শ স্টাডি কিউব। উল্টে রাখলেই স্বয়ংক্রিয়ভাবে টাইমার চালু হয়। ভাইব্রেশন ও মিউট নোটিফিকেশন মোড রয়েছে।',
                'price' => 1100,
                'discount_price' => 850,
                'stock' => 40,
                'warranty' => '৬ মাসের ওয়ারেন্টি',
                'badge' => 'নতুন',
                'rating' => 4.75,
                'reviews_count' => 21,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'টাইম প্রিসেট' => '৫, ১৫, ২৫, ৪৫ মিনিট কিউব ফ্লিপ',
                    'চার্জিং' => 'Type-C রিচার্জেবল লিথিয়াম ব্যাটারি',
                    'মোড' => 'সাউন্ড ও ভাইব্রেশন ডুয়াল মোড',
                ],
            ],
            [
                'title' => 'ইউগ্রিন এরগনোমিক ভার্টিকাল রিচার্জেবল ব্লুটুথ মাউস',
                'slug' => 'ugreen-ergonomic-vertical-bluetooth-mouse',
                'type' => 'electronics',
                'category_id' => $elecCatModels['desk-gadgets']->id,
                'brand' => 'Ugreen',
                'model' => 'ErgoPro Wireless 4000 DPI',
                'sku' => 'ELC-MOU-06',
                'summary' => 'হাতের কব্জির ব্যথা প্রতিরোধে ন্যাচারাল হ্যান্ডশেক পজিশন ভার্টিকাল ওয়্যারলেস মাউস।',
                'description' => 'দীর্ঘক্ষণ কম্পিউটারে বই লেখা, এডিটিং বা অফিসের কাজের জন্য চিকিৎসকদের দ্বারা প্রশংসিত এরগনোমিক মাউস। এর ৫৭ ডিগ্রি কোণ হাতের স্বাভাবিক অবস্থান ধরে রাখে। সাইলেন্ট ক্লিক সিস্টেম।',
                'price' => 2400,
                'discount_price' => 1950,
                'stock' => 22,
                'warranty' => '১ বছর রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.9,
                'reviews_count' => 19,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ডিপিআই' => '1000 - 1600 - 2400 - 4000 Adjustable',
                    'কানেক্টিভিটি' => 'Bluetooth 5.0 + 2.4G USB ডঙ্গেল',
                    'ব্যাটারি' => 'রিচার্জেবল ৫০০ এমএএইচ (৩ মাস ব্যাকআপ)',
                ],
            ],
            [
                'title' => 'ডেস্কটপ মিনি এয়ার পিউরিফায়ার ও নয়েজলেস রিডিং ফ্যান',
                'slug' => 'desktop-mini-air-purifier-reading-fan',
                'type' => 'electronics',
                'category_id' => $elecCatModels['reading-lights']->id,
                'brand' => 'Baseus',
                'model' => 'Ocean Desk Whisper',
                'sku' => 'ELC-FAN-07',
                'summary' => 'পড়ার টেবিল শান্ত ও ঠাণ্ডা রাখার জন্য আল্ট্রা-সাইলেন্ট রিচার্জেবল ফ্যান উইথ সফট নাইট লাইট।',
                'description' => 'স্টাডি টেবিল ও বেডসাইডের জন্য উপযুক্ত মিনি রিচার্জেবল টেবিল ফ্যান। কোন রকম শব্দ তৈরি না করে শান্ত হাওয়া দেয়। ৪টি স্পিড মোড এবং বিল্ট-ইন সফট ওয়ার্ম রিডিং লাইট রয়েছে।',
                'price' => 1850,
                'discount_price' => 1450,
                'stock' => 35,
                'warranty' => '৬ মাসের ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 17,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি' => '4000mAh Li-ion (১৬ ঘন্টা ব্যাকআপ)',
                    'শব্দের মাত্রা' => '২০ ডেসিবেলের নিচে (অত্যন্ত শান্ত)',
                    'চার্জিং' => 'USB Type-C',
                ],
            ],
        ];

        foreach ($electronicsProducts as $prod) {
            Product::updateOrCreate(
                ['slug' => $prod['slug']],
                $prod
            );
        }

        // 4. Stationery Products
        $stationeryProducts = [
            [
                'title' => 'আইডিয়া রয়াল এক্সিকিউটিভ ভিন্টেজ লেদার ডায়েরি (২০০ পেজ)',
                'slug' => 'idea-royal-executive-vintage-leather-diary',
                'type' => 'stationery',
                'category_id' => $statCatModels['diaries-notebooks']->id,
                'brand' => 'Idea Stationery',
                'model' => 'Royal Heritage Edition',
                'sku' => 'STN-DIR-01',
                'summary' => 'হাতে তৈরি জেনুইন লেদার কভার এবং ১০০ জিএসএম প্রিমিয়াম আইভরি নো-ব্লিড পেপার নোটবুক।',
                'description' => 'প্রতিদিনের ভাবনা, প্ল্যানিং ও গবেষণার নোট লিপিবদ্ধ করার জন্য অসাধারণ এক ভিন্টেজ ডায়রি। প্রিমিয়াম হ্যান্ড-স্টিচড বাইন্ডিং, রিবন বুকমার্ক এবং অ্যান্টিক মেটাল ক্ল্যাপ স্টাইল একে অনন্য রূপ দিয়েছে। কালির কলমে লিখলেও পেছনের পৃষ্ঠায় কালি ছড়ায় না।',
                'price' => 950,
                'discount_price' => 750,
                'stock' => 80,
                'warranty' => 'লাইফটাইম বাইন্ডিং গ্যারান্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.95,
                'reviews_count' => 74,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => 'A5 (5.8 x 8.3 ইঞ্চি)',
                    'পৃষ্ঠা সংখ্যা' => '২০০ পৃষ্ঠা (১০০ শিট)',
                    'কাগজের মান' => '১০০ GSM ফাউন্টেন পেন ফ্রেন্ডলি আইভরি পেপার',
                    'কভার' => 'হ্যান্ডক্রাফটেড প্রিমিয়াম পিইউ লেদার',
                ],
            ],
            [
                'title' => 'পার্কার জটার অরিজিনালস স্টেইনলেস স্টিল ফাউন্টেন পেন সেট',
                'slug' => 'parker-jotter-stainless-steel-fountain-pen-set',
                'type' => 'stationery',
                'category_id' => $statCatModels['pens-calligraphy']->id,
                'brand' => 'Parker',
                'model' => 'Jotter Originals Chrome Trim',
                'sku' => 'STN-PEN-02',
                'summary' => 'মসৃণ হাতের লেখা ও স্বাক্ষরের জন্য ক্লাসিক পার্কার স্টেইনলেস স্টিল নিব ফাউন্টেন পেন।',
                'description' => 'বিশ্ববিখ্যাত পার্কার ব্র্যান্ডের ক্লাসিক ফাউন্টেন পেন। স্টেইনলেস স্টিলের সূক্ষ্ম নিব হাতের লেখাকে করে তোলে দৃষ্টিনন্দন ও গতিশীল। উপহার ও ব্যক্তিগত ব্যবহারের জন্য প্রিমিয়াম গিফট বক্স সহ সরবরাহ করা হয়।',
                'price' => 2200,
                'discount_price' => 1850,
                'stock' => 50,
                'warranty' => '২ বছরের ইন্টারন্যাশনাল ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 61,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'নিব সাইজ' => 'মিডিয়াম (M) স্টেইনলেস স্টিল',
                    'কালি সিস্টেম' => 'কার্ট্রিজ ও পিস্টন কনভার্টার উভয়ই ব্যবহারযোগ্য',
                    'বডি' => 'ব্রাশড মেটাল ও ক্রোম ফিনিশ',
                    'ইনক্লুডেড' => '১টি ব্লু ইনক কার্ট্রিজ + লাক্সারি গিফট বক্স',
                ],
            ],
            [
                'title' => 'প্রফেশনাল ওয়াটারকালার ও স্কেচিং প্যাড ৩০০ জিএসএম (কোল্ড প্রেস)',
                'slug' => 'professional-watercolor-sketch-pad-300gsm',
                'type' => 'stationery',
                'category_id' => $statCatModels['art-sketchbooks']->id,
                'brand' => 'Baohong',
                'model' => 'Academy 100% Cotton 300GSM',
                'sku' => 'STN-ART-03',
                'summary' => '১০০% কটন কোল্ড প্রেসড অ্যাসিড-ফ্রি প্রফেশনাল ওয়াটারকালার ও ড্রয়িং আর্ট পেপার প্যাড।',
                'description' => 'চিত্রশিল্পী ও আর্ট প্রেমীদের জন্য আদর্শ ওয়াটারকালার প্যাড। ভারী পানির ব্যবহারে কাগজ ফোলে না বা কুঁচকে যায় না। ওয়াটারকালার, গোয়াশ, অ্যাক্রিলিক ও কালির ড্রয়িংয়ের জন্য নিখুঁত টেক্সচার।',
                'price' => 1400,
                'discount_price' => 1150,
                'stock' => 35,
                'warranty' => 'অ্যাসিড-ফ্রি নন-ইয়েলোয়িং গ্যারান্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.88,
                'reviews_count' => 32,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পেপার ওজন' => '৩০০ GSM (কোল্ড প্রেস টেক্সচার)',
                    'সাইজ' => 'A4 (21 x 29.7 cm)',
                    'শিট সংখ্যা' => '২০ শিট ব্লক বাউন্ড',
                    'উপাদান' => '১০০% কটন ফাইবার',
                ],
            ],
            [
                'title' => 'ভিন্টেজ ব্রাস মেটাল বুকমার্ক ও রুফটপ রিডিং মার্কার সেট (৪ পিস)',
                'slug' => 'vintage-brass-metal-bookmark-set-4pcs',
                'type' => 'stationery',
                'category_id' => $statCatModels['bookmarks-accessories']->id,
                'brand' => 'Idea Craft',
                'model' => 'Classic Heritage Brass Set',
                'sku' => 'STN-BMK-04',
                'summary' => 'বইপ্রেমীদের জন্য খোদাই করা এন্টিক ব্রাস মেটাল আর্ট বুকমার্ক ও সিল্ক ট্যাসেল সমন্বিত সেট।',
                'description' => 'বই পড়ার আনন্দ বহুগুণ বাড়িয়ে দিতে চার ভিন্ন স্থাপত্য নকশায় খোদাই করা চমৎকার ব্রাস বুকমার্ক। বইয়ের পাতার কোনো ক্ষতি করে না এবং বছরের পর বছর উজ্জ্বলতা বজায় রাখে। উপহার দেওয়ার জন্য সেরা পছন্দ।',
                'price' => 650,
                'discount_price' => 480,
                'stock' => 100,
                'warranty' => 'রাস্ট-প্রুফ লাইফটাইম গ্যারান্টি',
                'badge' => 'সেরা উপহার',
                'rating' => 4.95,
                'reviews_count' => 48,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মেটেরিয়াল' => 'পিউর ব্রাস ও গোল্ডেন ইলেক্ট্রোপ্লেটিং',
                    'পিস সংখ্যা' => '৪টি ভিন্ন ডিজাইনের বুকমার্ক',
                    'প্যাকেজিং' => 'ম্যাগনেটিক গিফট বক্স',
                ],
            ],
            [
                'title' => 'মাল্টি-ফাংশনাল উডেন ডেস্ক অর্গানাইজার ও পেন হোল্ডার',
                'slug' => 'multi-functional-wooden-desk-organizer',
                'type' => 'stationery',
                'category_id' => $statCatModels['organizers-storage']->id,
                'brand' => 'Idea Craft',
                'model' => 'EcoWood Desk Caddy Deluxe',
                'sku' => 'STN-ORG-05',
                'summary' => 'টেবিলের কলম, মার্কার, স্টিকি নোট, ফোন ও খাতা সাজিয়ে রাখার ন্যাচারাল উড ডেস্ক ক্যাডি।',
                'description' => 'পড়ার টেবিল গুছিয়ে রাখার সর্বাধুনিক সমাধান। এতে রয়েছে ৯টি পেন স্লট, ৩টি স্টোরেজ কম্পার্টমেন্ট এবং ড্রয়ার। পরিবেশবান্ধব সলিড কাঠ দিয়ে নিখুঁত ফিনিশিংয়ে তৈরি।',
                'price' => 1350,
                'discount_price' => 1050,
                'stock' => 40,
                'warranty' => '১ বছরের স্থায়িত্ব ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.82,
                'reviews_count' => 26,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মেটেরিয়াল' => 'ইকো-ফ্রেন্ডলি ব্যাম্বু উড',
                    'সাইজ' => '২৫ x ১৫ x ১১ সেন্টিমিটার',
                    'কম্পার্টমেন্ট' => '৯টি পেন স্লট, ১টি ড্রয়ার, ২টি ওপেন ট্রে',
                ],
            ],
            [
                'title' => 'টমবো ডুয়াল ব্রাশ পেন ১২ কালার আর্ট মার্কার সেট',
                'slug' => 'tombow-dual-brush-pen-12-color-set',
                'type' => 'stationery',
                'category_id' => $statCatModels['pens-calligraphy']->id,
                'brand' => 'Tombow',
                'model' => 'ABT Dual Brush Pastel & Primary',
                'sku' => 'STN-PEN-06',
                'summary' => 'ক্যালিগ্রাফি, লেটারিং ও ড্রয়িংয়ের জন্য জাপানি ডুয়াল ব্রাশ ও ফাইন টিপ মার্কার পেন সেট।',
                'description' => 'ক্যালিগ্রাফি শিল্পী ও নোট প্রস্তুতকারীদের প্রথম পছন্দ টমবো ডুয়াল ব্রাশ পেন। একদিকে ফ্লেক্সিবল ব্রাশ নিব এবং অন্যদিকে ০.৮ মিমি ফাইন টিপ। ওয়াটার-বেসড ব্লেন্ডেবল কালি।',
                'price' => 2800,
                'discount_price' => 2350,
                'stock' => 30,
                'warranty' => 'অরিজিনাল জাপান ইমপোর্টেড',
                'badge' => 'নতুন',
                'rating' => 4.96,
                'reviews_count' => 41,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্র্যান্ড অরিজিন' => 'টমবো, জাপান',
                    'কালার সেট' => '১২টি ভাইব্র্যান্ট শেডস',
                    'নিব টাইপ' => 'ডুয়াল টিপ (ব্রাশ ও ফাইন টিপ)',
                ],
            ],
            [
                'title' => 'আইডিয়া উইকলি ও মান্থলি স্টাডি হ্যাবিট ট্র্যাকার প্ল্যানার',
                'slug' => 'idea-weekly-monthly-study-habit-tracker-planner',
                'type' => 'stationery',
                'category_id' => $statCatModels['diaries-notebooks']->id,
                'brand' => 'Idea Stationery',
                'model' => 'Undated Productivity Planner',
                'sku' => 'STN-PLN-07',
                'summary' => 'স্টুডেন্ট ও চাকরি প্রার্থীদের রুটিন, লক্ষ্য এবং পড়ার অগ্রগতি ট্র্যাক করার আধুনিক প্ল্যানার।',
                'description' => 'লক্ষ্য অর্জনের জন্য নিখুঁত পরিকল্পনা অপরিহার্য। এই আনডেটেড প্ল্যানারে রয়েছে মাসিক গোল প্ল্যানিং, সাপ্তাহিক শিডিউল, ডেইলি রুটিন চেকলিস্ট এবং ডেইলি হ্যাবিট ট্র্যাকার। যেকোনো মাস থেকেই ব্যবহার শুরু করা যায়।',
                'price' => 750,
                'discount_price' => 550,
                'stock' => 90,
                'warranty' => 'স্যাটিসফ্যাকশন গ্যারান্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 59,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => 'B5 সাইজ',
                    'পৃষ্ঠা' => '১৬০ পৃষ্ঠা ১০০ GSM পেপার',
                    'লেআউট' => 'মান্থলি + উইকলি + হ্যাবিট ট্র্যাকার',
                    'বাইন্ডিং' => 'গোল্ডেন স্পাইরাল ওয়্যার বাইন্ডিং',
                ],
            ],
        ];

        foreach ($stationeryProducts as $prod) {
            Product::updateOrCreate(
                ['slug' => $prod['slug']],
                $prod
            );
        }
    }
}
