<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class HomeApplianceSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Home Appliance & Gadget Categories (ক্যাটাগরি অনুসারে পেজে স্লাইডার রো)
        $categories = [
            [
                'name' => 'বাড়ির রান্না ও কিচেন অ্যাপ্লায়েন্স',
                'slug' => 'kitchen-appliances',
                'type' => 'electronics',
                'description' => 'রাইস কুকার, ইন্ডাকশন চুলা, ব্লেন্ডার, প্রেসার কুকার, এয়ার ফ্রায়ার ও আধুনিক রান্নার সামগ্রী',
                'icon' => 'fas fa-utensils',
                'sort_order' => 1,
            ],
            [
                'name' => 'ফ্যান ও হোম কুলিং সামগ্রী',
                'slug' => 'cooling-fans',
                'type' => 'electronics',
                'description' => 'রিচার্জেবল টেবিল ফ্যান, পেডেস্টাল ফ্যান, এনার্জি সেভিং সিলিং ফ্যান, নেক ফ্যান ও মিস্ট ফ্যান',
                'icon' => 'fas fa-fan',
                'sort_order' => 2,
            ],
            [
                'name' => 'ফাস্ট চার্জার, পাওয়ার ব্যাংক ও গ্যাজেট',
                'slug' => 'chargers-gadgets',
                'type' => 'electronics',
                'description' => 'GaN ফাস্ট চার্জার, ২০০০০mAh পাওয়ার ব্যাংক, ১০০W ফাস্ট কেবল ও ওয়্যারলেস চার্জিং ডক',
                'icon' => 'fas fa-bolt',
                'sort_order' => 3,
            ],
            [
                'name' => 'স্মার্ট মাল্টিপ্লাগ ও ইলেকট্রিক এক্সেসরিজ',
                'slug' => 'multiplugs-accessories',
                'type' => 'electronics',
                'description' => 'ইউএসবি মাল্টিপ্লাগ, এক্সটেনশন সকেট, সার্জ প্রটেক্টর ও ইউনিভার্সাল ট্রাভেল এডাপ্টার',
                'icon' => 'fas fa-plug',
                'sort_order' => 4,
            ],
            [
                'name' => 'হোম ক্লিনিং ও ভ্যাকুয়াম ক্লিনার',
                'slug' => 'home-cleaning',
                'type' => 'electronics',
                'description' => 'হ্যান্ডহেল্ড পোর্টেবল ভ্যাকুয়াম ক্লিনার, কর্ডলেস স্টিক ভ্যাকুয়াম ও রোবট ক্লিনার',
                'icon' => 'fas fa-broom',
                'sort_order' => 5,
            ],
            [
                'name' => 'রুম কেয়ার, স্টিম আয়রন ও লাইফস্টাইল',
                'slug' => 'room-care-lifestyle',
                'type' => 'electronics',
                'description' => 'হ্যান্ডহেল্ড স্টিম আয়রন, আল্ট্রাসনিক এয়ার হিউমিডিফায়ার, অটো ওয়াটার পাম্প ও মসকুইটো কিলার ল্যাম্প',
                'icon' => 'fas fa-wind',
                'sort_order' => 6,
            ],
        ];

        $catModels = [];
        foreach ($categories as $cat) {
            $catModels[$cat['slug']] = ProductCategory::updateOrCreate(
                ['slug' => $cat['slug'], 'type' => 'electronics'],
                $cat
            );
        }

        // Clean up previous electronics products to avoid unique slug collisions
        Product::where('type', 'electronics')->delete();

        // 2. Comprehensive Home Appliances, Fans, Chargers & Gadgets
        $appliances = [
            // ══════════════════════════════════════════════════════════════
            // ১. বাড়ির রান্না ও কিচেন অ্যাপ্লায়েন্স (Kitchen & Cooking)
            // ══════════════════════════════════════════════════════════════
            [
                'id' => 1,
                'title' => 'প্যানাসনিক ডিজিটাল স্মার্ট অটোমেটিক রাইস কুকার ১.৮ লিটার',
                'slug' => 'panasonic-digital-smart-rice-cooker-1-8l',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Panasonic',
                'model' => 'SR-DF181 Digital Fuzzy Logic',
                'sku' => 'ELC-KTN-01',
                'summary' => 'ভাত ঝরঝরে ও গরম রাখার অটো-ওয়ার্ম ফাংশনসহ নন-স্টিক কোটিংযুক্ত ডিজিটাল রাইস কুকার।',
                'description' => 'প্যানাসনিক ডিজিটাল স্মার্ট রাইস কুকার স্বয়ংক্রিয়ভাবে চালের ধরন বুঝে রান্না করে। এতে রয়েছে স্টিমিং বাস্কেট, যার মাধ্যমে ভাত রান্নার পাশাপাশি ডিম, সবজি বা মোমো সহজেই ভাপে সেদ্ধ করা যায়।',
                'price' => 4800,
                'discount_price' => 3990,
                'stock' => 35,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 62,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '১.৮ লিটার (১০ কাপ চাল)',
                    'পাওয়ার' => '৭৫০ ওয়াট বিদ্যুৎ সাশ্রয়ী',
                    'ইনার পট' => 'আল্ট্রা নন-স্টিক কোটিং',
                    'মোড' => 'হোয়াইট রাইস, ব্রাউন রাইস, পরিজ ও স্টিম',
                    'অটো শাট-অফ' => 'থার্মাল সেন্সর কন্ট্রোল',
                ],
            ],
            [
                'id' => 2,
                'title' => 'মিয়াকে স্মার্ট ইন্ডাকশন ও ইনফ্রারেড চুলা ২২০০ ওয়াট',
                'slug' => 'miyako-smart-induction-cooker-2200w',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Miyako',
                'model' => 'ATC-2200 Smart Touch',
                'sku' => 'ELC-KTN-02',
                'summary' => 'বিদ্যুৎ সাশ্রয়ী দ্রুত রান্নার জন্য টাচ কন্ট্রোল প্যানেলসহ প্রিমিয়াম ক্রিস্টাল গ্লাস টপ চুলা।',
                'description' => 'গ্যাস সংযোগের ঝামেলা ছাড়াই সব ধরনের রান্নার আধুনিক সমাধান। ৮টি প্রি-সেট কুকিং মোড, চাইল্ড লক ও ৩ ঘণ্টা টাইমার অপশন রয়েছে। যেকোনো মেটাল ও স্টিল পাত্রে সমানভাবে তাপ পৌঁছে দেয়।',
                'price' => 4700,
                'discount_price' => 3890,
                'stock' => 40,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের সার্ভিস ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.8,
                'reviews_count' => 49,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'cover_image' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাওয়ার' => '২২০০ ওয়াট হাই এফিশিয়েন্সি',
                    'টপ প্লেট' => 'এ-গ্রেড ব্ল্যাক ক্রিস্টাল গ্লাস',
                    'কন্ট্রোল' => 'ডিজিটাল টাচ ও এলইডি ডিসপ্লে',
                    'সেফটি' => 'চাইল্ড লক ও ওভারহিট প্রটেকশন',
                    'টাইমার' => '০-১৮০ মিনিট অ্যাডজাস্টেবল',
                ],
            ],
            [
                'id' => 3,
                'title' => 'ফিলিপস ডেইলি কালেকশন ৩-ইন-১ ফুড ব্লেন্ডার ও জুসার',
                'slug' => 'philips-daily-collection-3-in-1-blender',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Philips',
                'model' => 'HR2056/00 Daily Collection',
                'sku' => 'ELC-KTN-03',
                'summary' => 'মসলা গুঁড়ো, স্মুদি ও ফলের জুস তৈরির শক্তিশালী ৪৫০ ওয়াট মোটরযুক্ত ৩-ইন-১ ব্লেন্ডার।',
                'description' => 'ফিলিপস ৩-ইন-১ ফুড ব্লেন্ডার দৈনন্দিন রান্নার প্রস্তুতি করে তোলে অত্যন্ত সহজ। মজবুত স্টেইনলেস স্টিল ৪-স্টার ব্লেড বরফ ও শক্ত মসলাও মুহূর্তেই গুঁড়ো করে। সহজে পরিষ্কার করার মতো আনব্রেকেবল জার অন্তর্ভুক্ত।',
                'price' => 4900,
                'discount_price' => 3950,
                'stock' => 30,
                'stock_status' => 'in_stock',
                'warranty' => '২ বছরের ইন্টারন্যাশনাল ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 64,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 3,
                'cover_image' => 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মোটর পাওয়ার' => '৪৫০ ওয়াট হাই-টর্ক',
                    'জার সংখ্যা' => '৩টি জার (বড় জুসার, মিডিয়াম চপার, মশলা গ্রাইন্ডার)',
                    'ব্লেড' => 'প্রোব্লেন্ড ৪-স্টার স্টেইনলেস স্টিল',
                    'স্পিড লেভেল' => 'পালস ফাংশনসহ মাল্টি-স্পিড',
                ],
            ],
            [
                'id' => 4,
                'title' => 'শাওমি মিজিয়া স্মার্ট এয়ার ফ্রায়ার ৩.৫ লিটার ডিজিটাল ওভেন',
                'slug' => 'xiaomi-mijia-smart-air-fryer-3-5l',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Xiaomi',
                'model' => 'Mijia Smart 3.5L OLED',
                'sku' => 'ELC-KTN-04',
                'summary' => 'তেল ছাড়া স্বাস্থ্যকর ফ্রাই, বেকিং ও গ্রিলিংয়ের জন্য ওলেড ডিসপ্লেযুক্ত স্মার্ট এয়ার ফ্রায়ার।',
                'description' => '৮৫% কম তেলে ক্রিস্পি ও মুখরোচক খাবার তৈরির নির্ভরযোগ্য সমাধান। ওলেড টাচ ডিসপ্লে দিয়ে তাপমাত্রা ও টাইমার নিয়ন্ত্রণ করা যায়। মি হোম অ্যাপের মাধ্যমে ১০০+ প্রি-সেট রেসিপি থেকে সরাসরি রান্না করা সম্ভব।',
                'price' => 8500,
                'discount_price' => 6990,
                'stock' => 20,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 5.0,
                'reviews_count' => 41,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 4,
                'cover_image' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '৩.৫ লিটার নন-স্টিক বাস্কেট',
                    'পাওয়ার' => '১৫০০ ওয়াট ৩৬০° হট এয়ার সার্কুলেশন',
                    'তাপমাত্রা' => '৪০° থেকে ২০০° সেলসিয়াস অ্যাডজাস্টেবল',
                    'কানেক্টিভিটি' => 'Wi-Fi ও Mi Home App সাপোর্ট',
                ],
            ],
            [
                'id' => 5,
                'title' => 'শাওমি স্মার্ট মাল্টিফাংশনাল ইলেকট্রিক কেটলি ১.৫ লিটার',
                'slug' => 'xiaomi-smart-electric-kettle-1-5l',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Xiaomi',
                'model' => 'Mijia 1.5L Kettle Pro',
                'sku' => 'ELC-KTN-05',
                'summary' => 'দ্রুত পানি গরম করার স্মার্ট অটো-কাট অফ ইলেকট্রিক কেটলি, ফুড-গ্রেড ৩০৪ স্টেইনলেস স্টিল বডি।',
                'description' => 'শাওমির এই ইলেকট্রিক কেটলিটি মাত্র ৪ থেকে ৫ মিনিটে ১.৫ লিটার পানি সম্পূর্ণ ফুটিয়ে তোলে। ডাবল লেয়ার অ্যান্টি-স্ক্যাল্ড ডিজাইন বাইরের বডি ঠান্ডা রাখে। অটোমেটিক পাওয়ার কাট-অফ এবং বয়েল-ড্রাই প্রটেকশন নিশ্চিত করে সর্বোচ্চ নিরাপত্তা।',
                'price' => 2800,
                'discount_price' => 2250,
                'stock' => 45,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের অফিসিয়াল ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.9,
                'reviews_count' => 52,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 5,
                'cover_image' => 'https://images.unsplash.com/photo-1594213114663-ddf3f2a02126?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '১.৫ লিটার',
                    'পাওয়ার' => '১৮০০ ওয়াট',
                    'মেটেরিয়াল' => '৩০৪ ফুড-গ্রেড স্টেইনলেস স্টিল',
                    'সেফটি' => 'অটো শাট-অফ ও ড্রাই-বয়েল প্রটেকশন',
                ],
            ],
            [
                'id' => 6,
                'title' => 'মিয়াকে ইলেকট্রিক মাল্টিফাংশনাল প্রেসার কুকার ৬ লিটার',
                'slug' => 'miyako-electric-multifunction-pressure-cooker-6l',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Miyako',
                'model' => 'EPC-6000 Digital Touch',
                'sku' => 'ELC-KTN-06',
                'summary' => 'কম সময়ে মাংস, বিরিয়ানি ও ডাল রান্নার জন্য ৭-লেভেল সেফটি ভালভযুক্ত স্মার্ট প্রেসার কুকার।',
                'description' => '৭০% পর্যন্ত সময় ও বিদ্যুৎ বাঁচিয়ে নিখুঁত রান্নার জন্য পারফেক্ট কিচেন সঙ্গী। এতে রয়েছে ১২টি ওয়ান-টাচ ডিজিটাল প্রি-সেট প্রোগ্রাম, নন-স্টিক ডাবল লেয়ার পট এবং অটোমেটিক প্রেসার কন্ট্রোল সিস্টেম।',
                'price' => 6800,
                'discount_price' => 5600,
                'stock' => 25,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের সার্ভিস ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.9,
                'reviews_count' => 38,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 6,
                'cover_image' => 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '৬ লিটার লার্জ পট',
                    'পাওয়ার' => '১০০০ ওয়াট ফাস্ট হিটিং',
                    'সেফটি' => '৭-লেভেল মাল্টি-লক প্রটেকশন সিস্টেম',
                    'ডিসপ্লে' => 'ডিজিটাল এলইডি ও ওয়ান-টাচ বাটন',
                ],
            ],
            [
                'id' => 7,
                'title' => 'প্রেস্টিজ নন-স্টিক ইলেকট্রিক রোটি ও পরোটা মেকার ১০০০ ওয়াট',
                'slug' => 'prestige-non-stick-electric-roti-maker-1000w',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Prestige',
                'model' => 'PRM-3.0 Shockproof Base',
                'sku' => 'ELC-KTN-07',
                'summary' => 'ঝটপট গোল ও নরম ফুলকো রুটি ও পরোটা তৈরির শক-প্রুফ ইলেকট্রিক রোটি মেকার।',
                'description' => 'মাত্র কয়েক সেকেন্ডে পাতলা ও নরম রুটি তৈরি করুন কোনো প্রকার বেলার ঝামেলা ছাড়াই। নন-স্টিক কোটিং প্লেটের কারণে রুটি আটকে যায় না এবং পরিষ্কার করা অত্যন্ত সহজ। এর শক-প্রুফ স্টেইনলেস স্টিল বডি নিশ্চিত করে শতভাগ নিরাপত্তা।',
                'price' => 3200,
                'discount_price' => 2550,
                'stock' => 32,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.7,
                'reviews_count' => 44,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 7,
                'cover_image' => 'https://images.unsplash.com/photo-1584990347449-399335efd543?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাওয়ার' => '১০০০ ওয়াট থার্মোস্ট্যাট কন্ট্রোল',
                    'প্লেট' => 'গ্রেনাইট নন-স্টিক ডাবল সাইড কোটিং',
                    'হ্যান্ডেল' => 'কুল-টাচ শক-প্রুফ গ্রিপ',
                    'ইন্ডিকেটর' => 'পাওয়ার ও রেডি এলইডি লাইট',
                ],
            ],
            [
                'id' => 8,
                'title' => 'ফিলিপস ডেইলি কালেকশন স্যান্ডউইচ মেকার ও টোস্টার',
                'slug' => 'philips-daily-collection-sandwich-maker-toaster',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Philips',
                'model' => 'HD2393/02 Cut & Seal',
                'sku' => 'ELC-KTN-08',
                'summary' => 'ক্রিস্পি কাট-অ্যান্ড-সিল ত্রিভুজ স্যান্ডউইচ তৈরির হাই-টেম্পারেচার নন-স্টিক টোস্টার।',
                'description' => 'সকালের নাস্তায় মজাদার ও ক্রিস্পি স্যান্ডউইচ তৈরির দ্রুততম সমাধান। এর কাট-অ্যান্ড-সিল প্লেট ভেতরের ফিলিং বা চিজ বাইরে পড়তে দেয় না। সহজ উল্লম্ব স্টোরেজ থাকায় কিচেনের কম জায়গায় রাখা যায়।',
                'price' => 3400,
                'discount_price' => 2750,
                'stock' => 28,
                'stock_status' => 'in_stock',
                'warranty' => '২ বছরের ইন্টারন্যাশনাল ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.8,
                'reviews_count' => 36,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 8,
                'cover_image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাওয়ার' => '৮২০ ওয়াট ফাস্ট হিটিং',
                    'প্লেট' => 'কাট ও সিল ট্রায়াঙ্গেল নন-স্টিক প্লেট',
                    'লক' => 'ইজি পুশ ডাউন লক সিস্টেম',
                    'কর্ড স্টোরেজ' => 'বিল্ট-ইন কর্ড র‍্যাপ সুবিধা',
                ],
            ],
            [
                'id' => 9,
                'title' => 'ব্রাউন মাল্টি-কুইক হ্যান্ড ব্লেন্ডার ও এগ বিটার',
                'slug' => 'braun-multiquick-hand-blender-egg-beater',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Braun',
                'model' => 'MQ100 Dip Hand Blender',
                'sku' => 'ELC-KTN-09',
                'summary' => 'ডাল ঘুটনি, কেকের ডিম বিট, স্যুপ ও বেবি ফুড পিউরির জন্য কম্প্যাক্ট পাওয়ারফুল হ্যান্ড ব্লেন্ডার।',
                'description' => 'জার্মান প্রযুক্তির পাওয়ারবেল টেকনোলজি স্প্ল্যাশ বা ছিটে যাওয়া ছাড়াই সেকেন্ডের মধ্যে যেকোনো মিশ্রণ প্রস্তুত করে। ওয়ান-টাচ স্পিড অ্যাক্টিভেশনের মাধ্যমে সহজে নিয়ন্ত্রণযোগ্য। সাথে রয়েছে পরিমাপের জন্য ৬০০ মিলি স্মুদি বিকার।',
                'price' => 3600,
                'discount_price' => 2890,
                'stock' => 22,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'নতুন',
                'rating' => 4.8,
                'reviews_count' => 29,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 9,
                'cover_image' => 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মোটর পাওয়ার' => '৪৫০ ওয়াট সাইলেন্ট ডিসি মোটর',
                    'ব্লেড' => 'পাওয়ারবেল আল্ট্রা-হার্ড স্টেইনলেস স্টিল',
                    'এক্সেসরিজ' => 'বিটার শ্যাফট ও ৬০০ মিলি মেজারিং বিকার',
                    'ওয়াশেবল' => 'ডিশওয়াশার সেফ পার্টস',
                ],
            ],

            // ══════════════════════════════════════════════════════════════
            // ২. ফ্যান ও হোম কুলিং সামগ্রী (Fans & Home Cooling)
            // ══════════════════════════════════════════════════════════════
            [
                'id' => 10,
                'title' => 'ডিফেন্ডার ১৬ ইঞ্চি হাই-স্পিড রিচার্জেবল পেডেস্টাল স্ট্যান্ড ফ্যান',
                'slug' => 'defender-16-inch-rechargeable-pedestal-stand-fan',
                'type' => 'electronics',
                'category_id' => $catModels['cooling-fans']->id,
                'brand' => 'Defender',
                'model' => '2980-HRS Rechargeable Pedestal 16"',
                'sku' => 'ELC-FAN-01',
                'summary' => 'লোডশেডিংয়ে টানা ৮ ঘণ্টা ব্যাকআপ, রিমোট কন্ট্রোল ও ব্রাইট এলইডি লাইটযুক্ত স্ট্যান্ড ফ্যান।',
                'description' => 'প্রচণ্ড গরমে নিরবচ্ছিন্ন শীতল বাতাসের জন্য ডিফেন্ডারের প্রিমিয়াম পেডেস্টাল ফ্যান। এতে রয়েছে শক্তিশালী ১২ ভোল্ট রিচার্জেবল ব্যাটারি, ৫-পাখা অ্যারোডাইনামিক ব্লেড, জরুরি লাইট এবং পূর্ণ দূরবর্তী রিমোট কন্ট্রোল সুবিধা।',
                'price' => 7500,
                'discount_price' => 6200,
                'stock' => 25,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের অফিসিয়াল ব্যাটারি ও মোটর ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 78,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'cover_image' => 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্লেড সাইজ' => '১৬ ইঞ্চি (৫ ব্লেড হাই এয়ারফ্লো)',
                    'ব্যাটারি' => '১২V ৪.৫Ah হেভি ডিউটি রিচার্জেবল',
                    'ব্যাকআপ' => 'লো স্পিডে ৮ ঘণ্টা, হাই স্পিডে ৪.৫ ঘণ্টা',
                    'কন্ট্রোল' => 'ওয়্যারলেস রিমোট ও ম্যানুয়াল টাচ প্যানেল',
                    'অসিলেশন' => '৯০ ডিগ্রি ওয়াইড অটো অসিলেশন',
                ],
            ],
            [
                'id' => 11,
                'title' => 'বেসাস সাইলেন্ট রিচার্জেবল ফোল্ডেবল ডেস্ক ও হোম ফ্যান',
                'slug' => 'baseus-silent-rechargeable-desk-home-fan',
                'type' => 'electronics',
                'category_id' => $catModels['cooling-fans']->id,
                'brand' => 'Baseus',
                'model' => 'Ocean Breeze Silent Fan',
                'sku' => 'ELC-FAN-02',
                'summary' => 'লোডশেডিংয়ে টানা ৮-১০ ঘণ্টা শীতল বাতাসের নিশ্চয়তাসহ ইউএসবি রিচার্জেবল পোর্টেবল ফ্যান।',
                'description' => 'ঘরের খাবার টেবিল, বেডসাইড বা বারান্দার জন্য উপযুক্ত শান্ত রিচার্জেবল ফ্যান। ব্রাশলেস মোটরের কারণে কোনো প্রকার শব্দ হয় না। ৪টি উইন্ড স্পিড এবং ১২০ ডিগ্রি অটো অসিলেশন সুবিধা রয়েছে।',
                'price' => 2400,
                'discount_price' => 1850,
                'stock' => 38,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের অফিসিয়াল রিপ্লেসমেন্ট',
                'badge' => 'হট ডিল',
                'rating' => 4.8,
                'reviews_count' => 84,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'cover_image' => 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি' => '৪০০০ mAh রিচার্জেবল লিথিয়াম',
                    'ব্যাকআপ টাইম' => '৮ থেকে ১০ ঘণ্টা',
                    'স্পিড মোড' => '৪টি লেভেল অ্যাডজাস্টেবল',
                    'চার্জিং' => 'Type-C USB চার্জিং',
                ],
            ],
            [
                'id' => 12,
                'title' => 'ভিশন সুপার এনার্জি সেভিং বিএলডিসি সিলিং ফ্যান রিমোটসহ',
                'slug' => 'vision-super-energy-saving-bldc-ceiling-fan',
                'type' => 'electronics',
                'category_id' => $catModels['cooling-fans']->id,
                'brand' => 'Vision',
                'model' => 'Super Saver 56 Inch BLDC Fan',
                'sku' => 'ELC-FAN-03',
                'summary' => '৬৫% পর্যন্ত বিদ্যুৎ সাশ্রয়ী ৩৫ ওয়াট বিএলডিসি মোটরযুক্ত প্রিমিয়াম অ্যালুমিনিয়াম সিলিং ফ্যান।',
                'description' => 'স্বাভাবিক সিলিং ফ্যানের অর্ধেকেরও কম বিদ্যুতে সর্বোচ্চ বাতাস প্রদান করে। রিমোট কন্ট্রোলের মাধ্যমে ১ থেকে ৬ লেভেল স্পিড, স্লিপ মোড ও টাইমার সেট করা যায়। ১০০% কপার ওয়্যারিং দীর্ঘস্থায়িত্ব নিশ্চিত করে।',
                'price' => 4800,
                'discount_price' => 3950,
                'stock' => 30,
                'stock_status' => 'in_stock',
                'warranty' => '২ বছরের অফিসিয়াল ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 51,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 3,
                'cover_image' => 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাওয়ার কনজাম্পশন' => 'মাত্র ৩৫ ওয়াট (৬৫% বিদ্যুৎ সাশ্রয়ী)',
                    'মোটর' => 'বিএলডিসি ১০০% খাঁটি কপার ওয়্যার',
                    'ব্লেড সাইজ' => '৫৬ ইঞ্চি অ্যান্টি-রাস্ট অ্যালুমিনিয়াম',
                    'রিমোট সুবিধা' => 'স্পিড, বুস্ট মোড ও টাইমার সুইচ',
                ],
            ],
            [
                'id' => 13,
                'title' => 'জিসুলাইফ আল্ট্রা-সাইলেন্ট রিচার্জেবল হ্যান্ডহেল্ড ও নেক ফ্যান',
                'slug' => 'jisulife-ultra-silent-rechargeable-neck-fan',
                'type' => 'electronics',
                'category_id' => $catModels['cooling-fans']->id,
                'brand' => 'Jisulife',
                'model' => 'FA35 Pro 360 Dual Turbine Neck Fan',
                'sku' => 'ELC-FAN-04',
                'summary' => 'হ্যান্ডস-ফ্রি ৩৬০ ডিগ্রি চারপাশের এয়ার আউটলেটসহ ৪৫০০ mAh রিচার্জেবল পোর্টেবল নেক ফ্যান।',
                'description' => 'বাইরে চলাফেরা, কিচেনে রান্না বা ভ্রমণের সময় হাত মুক্ত রেখে ঠান্ডা বাতাস উপভোগ করার সেরা গ্যাজেট। ব্লেডলেস টারবাইন প্রযুক্তি চুল আটকে যাওয়ার কোনো ঝুঁকি রাখে না। এক চার্জে চলে দীর্ঘ সময়।',
                'price' => 2600,
                'discount_price' => 2100,
                'stock' => 42,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.8,
                'reviews_count' => 69,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 4,
                'cover_image' => 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি ক্যাপাসিটি' => '৪৫০০ mAh ডুয়াল লিথিয়াম',
                    'ব্যাকআপ টাইম' => '৫ থেকে ১৬ ঘণ্টা (স্পিড ভেদে)',
                    'ডিজাইন' => 'হ্যান্ডস-ফ্রি আরামদায়ক সফট সিলিকন ব্যান্ড',
                    'চার্জিং পোর্ট' => 'Type-C ফাস্ট চার্জিং',
                ],
            ],
            [
                'id' => 14,
                'title' => 'ডিয়ারমা ওয়াটার মিস্ট রিচার্জেবল এয়ার কুলার ফ্যান',
                'slug' => 'deerma-water-mist-rechargeable-air-cooler-fan',
                'type' => 'electronics',
                'category_id' => $catModels['cooling-fans']->id,
                'brand' => 'Deerma',
                'model' => 'F500 Mist Cooling Fan 600ml',
                'sku' => 'ELC-FAN-05',
                'summary' => 'ঠান্ডা পানির বাষ্প স্প্রে করে ঘরের তাপমাত্রা কমানোর আল্ট্রাসনিক মিস্ট রিচার্জেবল ফ্যান।',
                'description' => 'শুষ্ক ও গরম আবহাওয়ায় তাৎক্ষণিক শীতল অনুভূতির জন্য এতে রয়েছে বরফ ও পানির ৬০০ মিলি ট্যাংক। বাতাস ছড়ানোর সাথে সাথে এটি সূক্ষ্ম কুয়াশার কণা স্প্রে করে ঘরকে এয়ার কন্ডিশনারের মতো আরামদায়ক করে তোলে।',
                'price' => 3200,
                'discount_price' => 2490,
                'stock' => 26,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের অফিসিয়াল রিপ্লেসমেন্ট',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.7,
                'reviews_count' => 34,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 5,
                'cover_image' => 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পানির ট্যাংক' => '৬০০ মিলি (বরফের টুকরো রাখার স্লটসহ)',
                    'মিস্ট স্প্রে' => 'আল্ট্রাসনিক ডুয়াল নজেল স্প্রেয়ার',
                    'উইন্ড স্পিড' => '৩টি স্পিড মোড ও ৭-কালার নাইট লাইট',
                    'পাওয়ার' => 'ইউএসবি Type-C প্লাগ ও রিচার্জেবল',
                ],
            ],
            [
                'id' => 15,
                'title' => 'বেসাস ক্লিপ-অন রিচার্জেবল মিনি টেবিল ও বেড ফ্যান',
                'slug' => 'baseus-clip-on-rechargeable-mini-table-bed-fan',
                'type' => 'electronics',
                'category_id' => $catModels['cooling-fans']->id,
                'brand' => 'Baseus',
                'model' => 'Clip & Stand 360 Rotation Fan',
                'sku' => 'ELC-FAN-06',
                'summary' => 'পড়ার টেবিল, বিছানার রেলিং বা কম্পিউটারে ক্লিপ করে আটকানোর ৩৬০° রোটেটিং ফ্যান।',
                'description' => 'যেকোনো প্রান্তে ক্লিপ দিয়ে সহজে আটকে দেওয়া যায় কিংবা টেবিলে স্ট্যান্ড হিসেবে রাখা যায়। ৩৬০ ডিগ্রি উল্লম্ব ও অনুভূমিক ঘূর্ণন নিশ্চিত করে প্রয়োজন অনুযায়ী বাতাসের সঠিক দিক নির্ধারণ।',
                'price' => 1950,
                'discount_price' => 1550,
                'stock' => 40,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 47,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 6,
                'cover_image' => 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি' => '২০০০ mAh রিচার্জেবল লিথিয়াম',
                    'ঘূর্ণন' => '৩৬০° অল-অ্যাঙ্গেল ম্যানুয়াল রোটেশন',
                    'মাউন্টিং' => 'স্ট্রং ক্লিপ গ্রিপ ও ফ্ল্যাট টেবিল বেস',
                    'শব্দ' => '২৫ ডেসিবেলের নিচে আল্ট্রা সাইলেন্ট',
                ],
            ],
            [
                'id' => 16,
                'title' => 'ওয়ালটন হাই স্পিড রিচার্জেবল টেবিল ফ্যান ১২ ইঞ্চি',
                'slug' => 'walton-high-speed-rechargeable-table-fan-12-inch',
                'type' => 'electronics',
                'category_id' => $catModels['cooling-fans']->id,
                'brand' => 'Walton',
                'model' => 'W12-RF Rechargeable Table Fan',
                'sku' => 'ELC-FAN-07',
                'summary' => '৬V ৪.৫Ah শক্তিশালী ব্যাটারি ব্যাকআপযুক্ত কম্প্যাক্ট ১২ ইঞ্চি হাই স্পিড টেবিল ফ্যান।',
                'description' => 'দেশীয় সেরা ব্র্যান্ড ওয়ালটনের পরীক্ষিত রিচার্জেবল ফ্যান। চার্জ ফুল হলে স্বয়ংক্রিয়ভাবে কাট-অফ হয়ে ব্যাটারি ভালো রাখে। টেবিল ও ডাইনিংয়ের জন্য আদর্শ সাইজ।',
                'price' => 4200,
                'discount_price' => 3450,
                'stock' => 20,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের অফিসিয়াল সার্ভিস ওয়ারেন্টি',
                'badge' => 'নতুন',
                'rating' => 4.7,
                'reviews_count' => 28,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 7,
                'cover_image' => 'https://images.unsplash.com/photo-1567928805192-d35d641494b8?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্লেড সাইজ' => '১২ ইঞ্চি হাই ফ্লো অ্যারো ব্লেড',
                    'ব্যাটারি' => '৬V ৪.৫Ah সিল্ড লেড অ্যাসিড',
                    'ব্যাকআপ' => '৪ থেকে ৬ ঘণ্টা নিরবচ্ছিন্ন বাতাস',
                    'ফিচার' => 'ওভারচার্জ ও ডিপ ডিসচার্জ প্রটেকশন',
                ],
            ],

            // ══════════════════════════════════════════════════════════════
            // ৩. ফাস্ট চার্জার, পাওয়ার ব্যাংক ও গ্যাজেট (Chargers & Gadgets)
            // ══════════════════════════════════════════════════════════════
            [
                'id' => 17,
                'title' => 'বেসাস গান৫ প্রো ৬৫ ওয়াট ৩-পোর্ট ফাস্ট চার্জার এডাপ্টার (GaN Charger)',
                'slug' => 'baseus-gan5-pro-65w-fast-charger-adapter',
                'type' => 'electronics',
                'category_id' => $catModels['chargers-gadgets']->id,
                'brand' => 'Baseus',
                'model' => 'GaN5 Pro 65W Quick Charger 2C+1A',
                'sku' => 'ELC-CHG-01',
                'summary' => 'ল্যাপটপ, ম্যাকবুক ও স্মার্টফোনের জন্য ৬৫W সুপারফাস্ট ৩-পোর্ট গ্যালিয়াম নাইট্রাইড চার্জার।',
                'description' => 'একসাথে ৩টি ডিভাইস দ্রুত চার্জ করার প্রিমিয়াম সল্যুশন। নতুন GaN 5 প্রযুক্তির কারণে সাইজে ছোট কিন্তু অসাধারণ ঠান্ডা থাকে। ম্যাকবুক প্রো ৩০ মিনিটে ৬০% চার্জ করতে সক্ষম। স্যামসাং ও আইফোনের সকল ফাস্ট চার্জিং প্রটোকল সাপোর্ট করে।',
                'price' => 2900,
                'discount_price' => 2350,
                'stock' => 48,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের ব্র্যান্ড রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 95,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'cover_image' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'আউটপুট পাওয়ার' => '৬৫ ওয়াট ম্যাক্সিমাম পিডি ফাস্ট চার্জ',
                    'পোর্ট' => '২টি Type-C + ১টি USB-A পোর্ট',
                    'প্রযুক্তি' => 'GaN V (Gallium Nitride) কুলিং চিপ',
                    'সামঞ্জস্য' => 'ল্যাপটপ, ম্যাকবুক, আইফোন, স্যামসাং ও শাওমি',
                    'ওজন' => 'মাত্র ১২০ গ্রাম কম্প্যাক্ট সাইজ',
                ],
            ],
            [
                'id' => 18,
                'title' => 'শাওমি ৩৩ ওয়াট সুপারফাস্ট পিডি ওয়াল চার্জার (Type-C + USB)',
                'slug' => 'xiaomi-33w-soniccharge-superfast-wall-charger',
                'type' => 'electronics',
                'category_id' => $catModels['chargers-gadgets']->id,
                'brand' => 'Xiaomi',
                'model' => 'SonicCharge 33W Fast Charger Dual Port',
                'sku' => 'ELC-CHG-02',
                'summary' => 'ডুয়াল পোর্ট ৩৩ ওয়াট কুইক চার্জার, পাওয়ার ডেলিভারি ৩.০ এবং টার্বো চার্জিং প্রযুক্তি।',
                'description' => 'শাওমি ও রেডমি ফোনের আসল টার্বো চার্জ গতি পেতে শতভাগ অরিজিনাল চার্জার এডাপ্টার। এটি ওভারভোল্টেজ ও অতিরিক্ত তাপ নিরোধক সুরক্ষা দিয়ে ফোন নিরাপদ রাখে। সাথে রয়েছে টাইপ-সি ফাস্ট কেবল।',
                'price' => 1600,
                'discount_price' => 1290,
                'stock' => 55,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের অফিসিয়াল রিপ্লেসমেন্ট',
                'badge' => 'হট ডিল',
                'rating' => 4.8,
                'reviews_count' => 74,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'cover_image' => 'https://images.unsplash.com/photo-1622445262464-84b14e572242?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাওয়ার' => '৩৩ ওয়াট ম্যাক্স টার্বো চার্জ',
                    'পোর্ট' => 'Type-C এবং USB-A ডুয়াল আউটপুট',
                    'প্রটোকল' => 'PD 3.0, QC 3.0, Mi Turbo Charge',
                    'সেফটি' => '৩২-লেয়ার মাল্টিপল সার্কিট গার্ড',
                ],
            ],
            [
                'id' => 19,
                'title' => 'রেমি ২০,০০০ mAh ডুয়াল পোর্ট ফাস্ট চার্জিং পাওয়ার ব্যাংক ২২.৫W',
                'slug' => 'redmi-20000mah-fast-charging-power-bank-22-5w',
                'type' => 'electronics',
                'category_id' => $catModels['chargers-gadgets']->id,
                'brand' => 'Redmi',
                'model' => '20000mAh Power Bank PB200LZM Fast',
                'sku' => 'ELC-CHG-03',
                'summary' => '২২.৫ ওয়াট টু-ওয়ে ফাস্ট চার্জিং এবং হাই ক্যাপাসিটি লিথিয়াম পলিমার ব্যাটারির পাওয়ার ব্যাংক।',
                'description' => 'ভ্রমণে বা দীর্ঘ সময় বাইরে থাকাকালীন যেকোনো ফোন ৪ থেকে ৫ বার ফুল চার্জ করার মতো বিশাল শক্তি। ডুয়াল ইনপুট এবং ডুয়াল আউটপুট থাকায় একই সাথে দুটি ফোন অতি দ্রুত চার্জ করা সম্ভব।',
                'price' => 2700,
                'discount_price' => 2190,
                'stock' => 50,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের অফিসিয়াল রিপ্লেসমেন্ট',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 110,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 3,
                'cover_image' => 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি ক্যাপাসিটি' => '২০,০০০ mAh লিথিয়াম পলিমার',
                    'আউটপুট' => '২২.৫W ম্যাক্সিমাম কুইক চার্জিং',
                    'ইনপুট' => 'Type-C ও Micro USB ইনপুট সাপোর্ট',
                    'ডিসপ্লে' => '৪-স্টেজ এলইডি চার্জ লেভেল ইন্ডিকেটর',
                ],
            ],
            [
                'id' => 20,
                'title' => 'বেসাস ম্যাগনেটিক ১০,০০০ mAh ওয়্যারলেস পাওয়ার ব্যাংক ২০W',
                'slug' => 'baseus-magnetic-10000mah-wireless-power-bank-20w',
                'type' => 'electronics',
                'category_id' => $catModels['chargers-gadgets']->id,
                'brand' => 'Baseus',
                'model' => 'Magnetic MagSafe Power Bank 20W PD',
                'sku' => 'ELC-CHG-04',
                'summary' => 'আইফোনের পেছনে ম্যাগনেটিক আটকে থাকার ১৫W ওয়্যারলেস ও ২০W Type-C কেবল পাওয়ার ব্যাংক।',
                'description' => 'স্লিম ও প্রিমিয়াম পকেট সাইজ পাওয়ার ব্যাংক। MagSafe প্রযুক্তি ফোনের সাথে শক্তভাবে লেগে থাকে তাই কেবল ছাড়াই সহজে চার্জ হয়। টাইপ-সি পোর্ট দিয়ে ল্যাপটপ বা অন্য ডিভাইসেও ২০W পিডি চার্জ করা যায়।',
                'price' => 3100,
                'discount_price' => 2490,
                'stock' => 35,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'নতুন',
                'rating' => 4.8,
                'reviews_count' => 42,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 4,
                'cover_image' => 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ওয়্যারলেস আউটপুট' => '১৫W ম্যাগনেটিক স্ন্যাপ চার্জিং',
                    'ক্যাবল আউটপুট' => '২০W PD Type-C কুইক চার্জ',
                    'ব্যাটারি' => '১০,০০০ mAh পলিমার সেল',
                    'ডিজাইন' => 'সফট সিলিকন ম্যাগনেটিক ব্যাকপ্যাক',
                ],
            ],
            [
                'id' => 21,
                'title' => 'ইউগ্রিন ১০০ ওয়াট পিডি ফাস্ট চার্জিং টাইপ-সি টু টাইপ-সি ক্যাবল (২ মিটার)',
                'slug' => 'ugreen-100w-pd-type-c-to-type-c-cable-2m',
                'type' => 'electronics',
                'category_id' => $catModels['chargers-gadgets']->id,
                'brand' => 'UGREEN',
                'model' => '100W PD Type-C Braided Cable 2M E-Marker',
                'sku' => 'ELC-CHG-05',
                'summary' => 'ল্যাপটপ, ম্যাকবুক ও ফ্ল্যাগশিপ ফোনের জন্য নাইলন ব্রেডেড ১০০W ই-মার্কার স্মার্ট ক্যাবল।',
                'description' => 'প্রিমিয়াম ব্রেডেড ক্যাবল যা সহজে প্যাঁচায় না বা নষ্ট হয় না। বিল্ট-ইন ই-মার্কার চিপ ভোল্টেজ নিখুঁতভাবে সমন্বয় করে ব্যাটারিকে ১০০% নিরাপদ রাখে। ডেটা ট্রান্সফার রেট ৪৮০ Mbps।',
                'price' => 850,
                'discount_price' => 650,
                'stock' => 60,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.9,
                'reviews_count' => 85,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 5,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সর্বোচ্চ পাওয়ার' => '১০০W (20V/5A) আল্ট্রা হাই পাওয়ার',
                    'মেটেরিয়াল' => 'ডাবল ব্রেডেড নাইলন ও অ্যালুমিনিয়াম প্লাগ',
                    'দৈর্ঘ্য' => '২ মিটার (৬.৬ ফুট)',
                    'চিপসেট' => 'E-Marker সেফটি চিপ',
                ],
            ],
            [
                'id' => 22,
                'title' => 'বেসাস ৩-ইন-১ ফাস্ট চার্জিং ডাটা ক্যাবল (Type-C, iPhone, Micro-USB)',
                'slug' => 'baseus-3-in-1-fast-charging-data-cable',
                'type' => 'electronics',
                'category_id' => $catModels['chargers-gadgets']->id,
                'brand' => 'Baseus',
                'model' => '3-in-1 Rapid Fast Charge Cable 1.2M 3.5A',
                'sku' => 'ELC-CHG-06',
                'summary' => 'এক ক্যাবলেই সব সমাধান—টাইপ-সি, আইফোন ও মাইক্রো ইউএসবি ৩.৫A ফাস্ট চার্জিং ক্যাবল।',
                'description' => 'একসাথে তিনটি ভিন্ন ধরনের ফোন চার্জ করার নিখুঁত সমাধান। টেকসই ব্রেডেড মেটেরিয়াল ও অ্যালয় কানেক্টর ক্যাবলটিকে ১০ গুণ বেশি দীর্ঘস্থায়ী করে।',
                'price' => 650,
                'discount_price' => 490,
                'stock' => 65,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.8,
                'reviews_count' => 92,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 6,
                'cover_image' => 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'কারেন্ট রেটিং' => '৩.৫A ম্যাক্সিমাম আউটপুট',
                    'কানেক্টর' => 'Type-C + Lightning (iOS) + Micro USB',
                    'দৈর্ঘ্য' => '১.২ মিটার প্রিমিয়াম ব্রেডেড',
                    'কালার' => 'ম্যাট ব্ল্যাক অ্যালুমিনিয়াম হাউজিং',
                ],
            ],
            [
                'id' => 23,
                'title' => 'জয়রুম ৩-ইন-১ ম্যাগনেটিক ফোল্ডেবল ওয়্যারলেস চার্জিং ডক',
                'slug' => 'joyroom-3-in-1-magnetic-foldable-wireless-charging-dock',
                'type' => 'electronics',
                'category_id' => $catModels['chargers-gadgets']->id,
                'brand' => 'Joyroom',
                'model' => 'JR-WQN01 3-in-1 Foldable Dock 15W',
                'sku' => 'ELC-CHG-07',
                'summary' => 'একসাথে ফোন, অ্যাপল/স্মার্টওয়াচ ও এয়ারবাডস চার্জ করার ফোল্ডেবল ম্যাগনেটিক চার্জিং স্ট্যান্ড।',
                'description' => 'ডেস্ক বা বেডসাইড টেবিলকে ক্যাবলের জঞ্জালমুক্ত রাখার আধুনিক গ্যাজেট। ফোল্ড করে পকেটে নিয়ে ভ্রমণ করা যায়। ম্যাগনেটিক গ্রিপ ফোনকে যেকোনো অ্যাঙ্গেলে দাঁড় করিয়ে রাখতে সাহায্য করে।',
                'price' => 3500,
                'discount_price' => 2850,
                'stock' => 24,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের অফিসিয়াল রিপ্লেসমেন্ট',
                'badge' => 'নতুন',
                'rating' => 4.9,
                'reviews_count' => 31,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 7,
                'cover_image' => 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'আউটপুট' => '১৫W ফোন + ৫W ওয়াচ + ৫W ইয়ারবাডস',
                    'ডিজাইন' => 'ফোল্ডেবল অ্যালুমিনিয়াম স্ট্যান্ড',
                    'সেফটি' => 'এফওডি অবজেক্ট ডিটেকশন ও ওভারহিট গার্ড',
                ],
            ],
            [
                'id' => 24,
                'title' => 'বেসাস ৬০ ওয়াট ডুয়াল পোর্ট ফাস্ট কার চার্জার এডাপ্টার',
                'slug' => 'baseus-60w-dual-port-fast-car-charger-adapter',
                'type' => 'electronics',
                'category_id' => $catModels['chargers-gadgets']->id,
                'brand' => 'Baseus',
                'model' => 'Golden Contactor Pro 60W Car Charger',
                'sku' => 'ELC-CHG-08',
                'summary' => 'গাড়ির মধ্যে ল্যাপটপ ও ফোন দ্রুত চার্জ করার ৬০W মেটাল অ্যালয় ডুয়াল পোর্ট কার চার্জার।',
                'description' => '১২V থেকে ২৪V সকল ধরনের গাড়ি ও মাইক্রোবাসের সাথে সামঞ্জস্যপূর্ণ। প্রিমিয়াম মেটাল বডি হওয়ায় কখনোই অতিরিক্ত গরম হয় না। চমৎকার সফট ব্লু অ্যাম্বিয়েন্ট লাইট নাইট ড্রাইভিংয়ে পোর্ট খুঁজে পেতে সাহায্য করে।',
                'price' => 1400,
                'discount_price' => 1100,
                'stock' => 36,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 40,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 8,
                'cover_image' => 'https://images.unsplash.com/photo-1593121923594-a69c0e3f8c7b?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মোট পাওয়ার' => '৬০ ওয়াট (৩০W Type-C + ৩০W USB-A)',
                    'ইনপুট' => '১২V-২৪V ইউনিভার্সাল কার সকেট',
                    'বডি' => 'অ্যানোডাইজড অ্যালুমিনিয়াম অ্যালয় বডি',
                ],
            ],

            // ══════════════════════════════════════════════════════════════
            // ৪. স্মার্ট মাল্টিপ্লাগ ও ইলেকট্রিক এক্সেসরিজ (Multiplugs)
            // ══════════════════════════════════════════════════════════════
            [
                'id' => 25,
                'title' => 'এলডিএনআইও ৪-আউটলেট স্মার্ট মাল্টিপ্লাগ ও ৪-ইউএসবি চার্জিং স্টেশন',
                'slug' => 'ldnio-4-outlet-smart-multiplug-4-usb-power-strip',
                'type' => 'electronics',
                'category_id' => $catModels['multiplugs-accessories']->id,
                'brand' => 'LDNIO',
                'model' => 'SC4407 Fast Charging Power Strip 2500W',
                'sku' => 'ELC-PLG-01',
                'summary' => '৪টি ইউনিভার্সাল সকেট ও ৪টি ফাস্ট ইউএসবি পোর্টযুক্ত ২৫০০ ওয়াট হেভি ডিউটি মাল্টিপ্লাগ।',
                'description' => 'ঘরের টিভি, ফ্রিজ, কম্পিউটার ও মোবাইল একসাথে সংযোগ করার নির্ভরযোগ্য এক্সটেনশন সকেট। এতে রয়েছে চাইল্ড সেফটি শাটল ডোর এবং ৮৫০°C ফায়ারপ্রুফ মেটেরিয়াল। বজ্রপাত ও ভোল্টেজ ওঠানামা রোধে বিল্ট-ইন সার্জ প্রটেক্টর।',
                'price' => 1950,
                'discount_price' => 1550,
                'stock' => 45,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 67,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'cover_image' => 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'রেটেড পাওয়ার' => '২৫০০ ওয়াট (১০A, ২৫০V)',
                    'সকেট আউটলেট' => '৪টি ইউনিভার্সাল প্লাগ সকেট',
                    'ইউএসবি পোর্ট' => '৪টি অটো-আইডি ১৭W ফাস্ট চার্জার',
                    'ক্যাবলের দৈর্ঘ্য' => '২ মিটার হেভি পিওর কপার কর্ড',
                    'নিরাপত্তা' => 'সার্জ ও স্পাইক প্রটেক্টর, চাইল্ড লক',
                ],
            ],
            [
                'id' => 26,
                'title' => 'বেসাস পাওয়ারকম্বো ১০০ ওয়াট ৬-ইন-১ ডেস্কটপ পাওয়ার স্ট্রিপ সকেট',
                'slug' => 'baseus-powercombo-100w-6-in-1-desktop-power-strip',
                'type' => 'electronics',
                'category_id' => $catModels['multiplugs-accessories']->id,
                'brand' => 'Baseus',
                'model' => 'PowerCombo 100W GaN 6-in-1 Desktop Strip',
                'sku' => 'ELC-PLG-02',
                'summary' => 'ডেস্কটপ সেটআপের জন্য ১০০W GaN ফাস্ট চার্জিং পোর্ট ও ২টি এসি আউটলেটযুক্ত স্মার্ট স্ট্রিপ।',
                'description' => 'পড়ার টেবিল বা অফিস ডেস্কের সকল ডিভাইসের একমাত্র কমপ্যাক্ট পাওয়ার সল্যুশন। ১০০W টাইপ-সি পোর্ট দিয়ে সরাসরি ম্যাকবুক ও ল্যাপটপ চার্জ করা যায় বাড়তি এডাপ্টার ছাড়াই। এতে রয়েছে স্মার্ট টাচ সুইচ।',
                'price' => 4800,
                'discount_price' => 3900,
                'stock' => 22,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'নতুন',
                'rating' => 4.9,
                'reviews_count' => 33,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 2,
                'cover_image' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'GaN পাওয়ার' => '১০০ ওয়াট আল্ট্রা ফাস্ট Type-C',
                    'পোর্ট সংখ্যা' => '২টি এসি সকেট + ২টি Type-C + ২টি USB-A',
                    'সুইচ' => 'স্মার্ট ডিজিটাল টাচ সেন্সর বাটন',
                ],
            ],
            [
                'id' => 27,
                'title' => 'স্মার্ট লাইফ ১৬এ ওয়াইফাই প্লাগ ও অটো টাইমার সকেট',
                'slug' => 'smart-life-16a-wifi-smart-plug-timer-socket',
                'type' => 'electronics',
                'category_id' => $catModels['multiplugs-accessories']->id,
                'brand' => 'Smart Life',
                'model' => '16A WiFi Smart Plug Energy Monitor',
                'sku' => 'ELC-PLG-03',
                'summary' => 'স্মার্টফোন দিয়ে যেকোনো এসি, গিজার বা ফ্যান অন/অফ এবং বিদ্যুৎ খরচ পরিমাপক স্মার্ট সকেট।',
                'description' => 'ঘরের বাইরে থেকেও মোবাইল অ্যাপ দিয়ে বাসার ইলেকট্রনিক যন্ত্রপাতি নিয়ন্ত্রণ করুন। টাইমার সেট করে নির্দিষ্ট সময়ে পানির পাম্প বা গিজার স্বয়ংক্রিয়ভাবে বন্ধ করা যায়। গুগল অ্যাসিস্ট্যান্ট ও আলেক্সা ভয়েস সাপোর্ট করে।',
                'price' => 1450,
                'discount_price' => 1150,
                'stock' => 38,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.8,
                'reviews_count' => 50,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 3,
                'cover_image' => 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'রেটিং' => '১৬A (৩৫০০ ওয়াট হেভি লোড)',
                    'কানেক্টিভিটি' => 'Wi-Fi 2.4GHz ও Tuya/Smart Life App',
                    'ফিচার' => 'রিয়েল-টাইম বিদ্যুৎ খরচ মিটার ও অটো টাইমার',
                ],
            ],
            [
                'id' => 28,
                'title' => 'ইউগ্রিন ইউনিভার্সাল অল-ইন-ওয়ান ইন্টারন্যাশনাল ট্রাভেল এডাপ্টার',
                'slug' => 'ugreen-universal-worldwide-travel-adapter',
                'type' => 'electronics',
                'category_id' => $catModels['multiplugs-accessories']->id,
                'brand' => 'UGREEN',
                'model' => 'Universal All-in-One Travel Adapter US/UK/EU/AU',
                'sku' => 'ELC-PLG-04',
                'summary' => '১৫০টিরও বেশি দেশের জন্য উপযোগী ইউনিভার্সাল কনভার্টার প্লাগ ও ফাস্ট ইউএসবি চার্জার।',
                'description' => 'বিদেশ ভ্রমণ কিংবা দেশে যেকোনো বিদেশি প্লাগের ডিভাইসের জন্য আবশ্যকীয় গ্যাজেট। স্লাইডার মেকানিজমের মাধ্যমে মুহূর্তেই ইউএস, ইউকে, ইউরোপ বা অস্ট্রেলিয়ান প্লাগে রূপান্তরিত হয়।',
                'price' => 1800,
                'discount_price' => 1390,
                'stock' => 40,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 45,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 4,
                'cover_image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'কমপ্যাটিবিলিটি' => 'ইউএস, ইউকে, ইইউ ও এইউ প্লাগ স্ট্যান্ডার্ড',
                    'আউটপুট' => '২টি ফাস্ট ইউএসবি + ইউনিভার্সাল এসি সকেট',
                    'নিরাপত্তা' => '৮A অটো-রিসেট ফিউজ প্রটেকশন',
                ],
            ],

            // ══════════════════════════════════════════════════════════════
            // ৫. হোম ক্লিনিং ও ভ্যাকুয়াম ক্লিনার (Home Cleaning)
            // ══════════════════════════════════════════════════════════════
            [
                'id' => 29,
                'title' => 'বেসাস রিচার্জেবল হ্যান্ডহেল্ড মিনি ভ্যাকুয়াম ক্লিনার ও ডাস্টার',
                'slug' => 'baseus-rechargeable-mini-handheld-vacuum-cleaner',
                'type' => 'electronics',
                'category_id' => $catModels['home-cleaning']->id,
                'brand' => 'Baseus',
                'model' => 'A2 Pro Cordless Handheld Vacuum',
                'sku' => 'ELC-CLN-01',
                'summary' => 'সোফা, পর্দা, পড়ার টেবিল ও হোম কর্নার পরিষ্কারের শক্তিশালী রিচার্জেবল পোর্টেবল ভ্যাকুয়াম।',
                'description' => 'কর্ডলেস এই মিনি ভ্যাকুয়াম ক্লিনার দিয়ে ঘরের যেকোনো কোণা, সোফা, কিবোর্ড ও বিছানার ধুলোবালি সহজেই পরিষ্কার করা যায়। এতে রয়েছে ওয়াশেবল হেপা ফিল্টার যা ৯৯.৭% সূক্ষ্ম ধুলিকণা আটকে রাখে।',
                'price' => 3200,
                'discount_price' => 2450,
                'stock' => 40,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের অফিসিয়াল ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.7,
                'reviews_count' => 73,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'cover_image' => 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাকশন পাওয়ার' => '৬০০০ Pa আল্ট্রা-স্ট্রং',
                    'ব্যাটারি' => '৬০০০ mAh রিচার্জেবল লিথিয়াম',
                    'চার্জিং' => 'Type-C ফাস্ট চার্জিং',
                    'ফিল্টার' => 'ওয়াশেবল HEPA ফিল্টারেশন',
                ],
            ],
            [
                'id' => 30,
                'title' => 'ডিয়ারমা কর্ডলেস হ্যান্ডহেল্ড স্টিক ভ্যাকুয়াম ক্লিনার',
                'slug' => 'deerma-cordless-handheld-stick-vacuum-cleaner',
                'type' => 'electronics',
                'category_id' => $catModels['home-cleaning']->id,
                'brand' => 'Deerma',
                'model' => 'VC20 Plus Cordless Stick Vacuum',
                'sku' => 'ELC-CLN-02',
                'summary' => 'মেঝে, কার্পেট ও সিলিংয়ের জন্য ১.১ কেজি ওজনের হালকা কর্ডলেস স্টিক ভ্যাকুয়াম।',
                'description' => 'তারের কোনো ঝামেলা ছাড়াই ঘরের প্রতিটি রুম সহজে পরিষ্কার করুন। উচ্চগতির ডিজিটাল মোটর فرش ও কার্পেটের ভেতর থেকে আটকে থাকা চুল ও ধুলা টেনে বের করে আনে। ৩টি বহুমুখী ব্রাশ অন্তর্ভুক্ত।',
                'price' => 6800,
                'discount_price' => 5490,
                'stock' => 20,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের সার্ভিস ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.8,
                'reviews_count' => 46,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'cover_image' => 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মোটর পাওয়ার' => '১৫০ ওয়াট হাই-এফিসিয়েন্সি ডিজিটাল মোটর',
                    'সাকশন' => '৮০০০ Pa সাইক্লোনিক সাকশন',
                    'ব্যাকআপ' => 'টানা ৩০ মিনিট নন-স্টপ ক্লিনিং',
                    'ওজন' => 'মাত্র ১.১ কেজি ফেদারওয়েট ডিজাইন',
                ],
            ],
            [
                'id' => 31,
                'title' => 'শাওমি মিজিয়া স্মার্ট রোবট ভ্যাকুয়াম ক্লিনার ও মপ',
                'slug' => 'xiaomi-mijia-smart-robot-vacuum-cleaner-mop',
                'type' => 'electronics',
                'category_id' => $catModels['home-cleaning']->id,
                'brand' => 'Xiaomi',
                'model' => 'Mijia 3C Laser Robot Vacuum Mop',
                'sku' => 'ELC-CLN-03',
                'summary' => 'ঘর স্বয়ংক্রিয়ভাবে ঝাড়ু ও মোছার জন্য এলডিএস লেজার ন্যাভিগেশনযুক্ত স্মার্ট রোবট ক্লিনার।',
                'description' => 'বাসায় কেউ না থাকলেও রোবট ক্লিনার পুরো ঘর নিখুঁতভাবে পরিষ্কার করে নিজ চার্জিং ডকে ফিরে যায়। স্মার্টফোন অ্যাপ দিয়ে যেকোনো নির্দিষ্ট রুম বা কর্নার সিলেক্ট করে ক্লিনিং শিডিউল করা সম্ভব।',
                'price' => 26500,
                'discount_price' => 22900,
                'stock' => 12,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 5.0,
                'reviews_count' => 28,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 3,
                'cover_image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাকশন পাওয়ার' => '৪০০০ Pa সুপার সাকশন',
                    'ম্যাপিং' => 'LDS 360° লেজার রেডার ন্যাভিগেশন',
                    'মোড' => 'ঝাড়ু ও পানি দিয়ে মোছা ২-ইন-১',
                    'কন্ট্রোল' => 'Mi Home App ও ভয়েস অ্যাসিস্ট্যান্ট',
                ],
            ],
            [
                'id' => 32,
                'title' => 'স্মার্ট রিচার্জেবল ইলেকট্রিক স্পিন স্ক্রাবার ক্লিনিং ব্রাশ',
                'slug' => 'smart-rechargeable-electric-spin-scrubber-cleaning-brush',
                'type' => 'electronics',
                'category_id' => $catModels['home-cleaning']->id,
                'brand' => 'Idea Home',
                'model' => 'Magic Spin Scrubber 360 Cordless',
                'sku' => 'ELC-CLN-04',
                'summary' => 'বাথরুম টাইলস, রান্নাঘরের সিঙ্ক ও গাড়ির চাকা নিখুঁত ধোয়ার রোটেটিং ইলেকট্রিক স্ক্রাবার।',
                'description' => 'হাতে ঘষে ঘষে কষ্ট করার দিন শেষ। এই শক্তিশালী স্পিন স্ক্রাবার ৩৬০ ডিগ্রি স্পিডে ঘুরে যেকোনো জেদি ময়লা ও দাগ মুহূর্তেই তুলে দেয়। এতে রয়েছে ৪টি আলাদা ব্রাশ হেড ও লম্বা এক্সটেনশন হ্যান্ডেল।',
                'price' => 2800,
                'discount_price' => 2190,
                'stock' => 30,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের ওয়ারেন্টি',
                'badge' => 'নতুন',
                'rating' => 4.7,
                'reviews_count' => 39,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 4,
                'cover_image' => 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মোটর স্পিড' => '৩০০ RPM হাই-টর্ক রোটেশন',
                    'ব্রাশ হেড' => '৪টি ভিন্ন সাইজের ইন্টারচেঞ্জেবল ব্রাশ',
                    'ব্যাটারি' => '২৫০০ mAh রিচার্জেবল ব্যাকআপ ৯০ মিনিট',
                    'হ্যান্ডেল' => 'অ্যাডজাস্টেবল টেলিস্কোপিক এক্সটেনশন রড',
                ],
            ],

            // ══════════════════════════════════════════════════════════════
            // ৬. রুম কেয়ার, স্টিম আয়রন ও লাইফস্টাইল (Room Care & Lifestyle)
            // ══════════════════════════════════════════════════════════════
            [
                'id' => 33,
                'title' => 'ডিয়ারমা হ্যান্ডহেল্ড ফোল্ডেবল জামাকাপড় স্টিম আয়রন',
                'slug' => 'deerma-portable-handheld-garment-steamer',
                'type' => 'electronics',
                'category_id' => $catModels['room-care-lifestyle']->id,
                'brand' => 'Deerma',
                'model' => 'HS007 Foldable Steamer Iron',
                'sku' => 'ELC-ROM-01',
                'summary' => 'দ্রুত কাপড়ের কুঁচকানো দূর করার ফোল্ডেবল হ্যান্ডহেল্ড হাই-টেম্পারেচার স্টিম আয়রন।',
                'description' => '১০ সেকেন্ডেই প্রস্তুত হওয়া শক্তিশালী স্টিম আয়রন। জামাকাপড় হ্যাঙ্গারে ঝুলিয়ে রেখেই সহজে ইস্ত্রি করা যায়। এর উচ্চ তাপমাত্রার বাষ্প কাপড়ের ৯৯.৯% ব্যাকটেরিয়া ও দুর্গন্ধ দূর করে।',
                'price' => 2800,
                'discount_price' => 2190,
                'stock' => 28,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 45,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'cover_image' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাওয়ার' => '৮০০ ওয়াট হাই-প্রেশার স্টিম',
                    'স্টিম স্পিড' => '১০ সেকেন্ডে বাষ্প আউটপুট',
                    'ডিজাইন' => 'ফোল্ডেবল ও ট্রাভেল-ফ্রেন্ডলি',
                    'ওজন' => 'মাত্র ৮০০ গ্রাম',
                ],
            ],
            [
                'id' => 34,
                'title' => 'ডিয়ারমা এফ৬২৮ আল্ট্রাসনিক এয়ার হিউমিডিফায়ার ৫ লিটার',
                'slug' => 'deerma-f628-ultrasonic-air-humidifier-5l',
                'type' => 'electronics',
                'category_id' => $catModels['room-care-lifestyle']->id,
                'brand' => 'Deerma',
                'model' => 'F628 Aroma Ultrasonic 5L',
                'sku' => 'ELC-ROM-02',
                'summary' => 'ঘরের আর্দ্রতা বজায় রাখতে এবং এসি রুমের শুষ্কতা দূর করতে আল্ট্রাসনিক কুয়াশা ও অ্যারোমা ডিফিউজার।',
                'description' => '৫ লিটার বড় পানির ট্যাংকের এই হিউমিডিফায়ার টানা ১২ ঘণ্টা নিরবচ্ছিন্ন আর্দ্রতা দেয়। এতে রয়েছে আলাদা অ্যারোমা অয়েল ট্রে, যার সাহায্যে ঘরে সুবাস ছড়ানো যায়। সাইলেন্ট অপারেশন ঘরের ঘুমের কোনো ব্যাঘাত ঘটায় না।',
                'price' => 2900,
                'discount_price' => 2290,
                'stock' => 33,
                'stock_status' => 'in_stock',
                'warranty' => '১ বছরের ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 58,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'cover_image' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '৫ লিটার লার্জ ট্যাংক',
                    'ময়েশ্চার আউটপুট' => '৩৫০ মিলি/ঘণ্টা মাইক্রো মিস্ট',
                    'নয়েজ লেভেল' => '৩৫ ডেসিবেলের নিচে আল্ট্রা-সাইলেন্ট',
                    'সুবিধা' => 'এসেনশিয়াল অয়েল ও অ্যারোমা ফ্রেন্ডলি',
                ],
            ],
            [
                'id' => 35,
                'title' => 'অটোমেটিক ইউএসবি রিচার্জেবল ড্রিংকিং ওয়াটার ডিসপেনসার পাম্প',
                'slug' => 'automatic-usb-drinking-water-dispenser-pump',
                'type' => 'electronics',
                'category_id' => $catModels['room-care-lifestyle']->id,
                'brand' => 'Idea Smart',
                'model' => 'QuickFlow USB Dispenser',
                'sku' => 'ELC-ROM-03',
                'summary' => '২০ লিটার পানির জারে সহজে ফিট হওয়া ওয়ান-টাচ ইলেকট্রিক ওয়াটার ডিসপেনসার পাম্প।',
                'description' => 'ভারী পানির জার তোলার ঝামেলা ছাড়াই ওয়ান-টাচে পানি পান করার আধুনিক ইলেকট্রিক ডিসপেনসার। ফুড-গ্রেড সিলিকন পাইপ এবং স্টেইনলেস স্টিল আউটলেট পানির সম্পূর্ণ বিশুদ্ধতা বজায় রাখে।',
                'price' => 1100,
                'discount_price' => 850,
                'stock' => 50,
                'stock_status' => 'in_stock',
                'warranty' => '১ মাসের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.9,
                'reviews_count' => 112,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 3,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি' => '১২০০ mAh রিচার্জেবল',
                    'ব্যাকআপ' => 'এক চার্জে ৫-৬টি ফুল জার',
                    'পাইপ' => 'ফুড-গ্রেড বিপিএ-মুক্ত সিলিকন',
                    'চার্জিং' => 'মাইক্রো ইউএসবি পোর্ট',
                ],
            ],
            [
                'id' => 36,
                'title' => 'স্মার্ট রিচার্জেবল আল্ট্রাভায়োলেট মসকুইটো কিলার ল্যাম্প ও ব্যাট',
                'slug' => 'smart-rechargeable-uv-mosquito-killer-lamp-bat',
                'type' => 'electronics',
                'category_id' => $catModels['room-care-lifestyle']->id,
                'brand' => 'Mosquito Guard',
                'model' => 'UV Insect Swatter & Night Trap 2-in-1',
                'sku' => 'ELC-ROM-04',
                'summary' => 'হ্যান্ডহেল্ড ইলেকট্রিক ব্যাট ও নাইট ট্র্যাপ ল্যাম্প—২-ইন-১ ইউভি রিচার্জেবল মসকুইটো কিলার।',
                'description' => 'রাতে বেসের উপর বসিয়ে দিলে ৩৬৫nm বেগুনি ইউভি আলো মশা ও পতঙ্গ আকর্ষণ করে সঙ্গে সঙ্গে নিধন করে। দিনে সাধারণ ইলেকট্রিক ব্যাট হিসেবে ব্যবহার করা যায়। ৩-লেয়ার সেফটি মেস শিশুদের স্পর্শ থেকে নিরাপদ রাখে।',
                'price' => 1450,
                'discount_price' => 1150,
                'stock' => 45,
                'stock_status' => 'in_stock',
                'warranty' => '১ মাসের ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.8,
                'reviews_count' => 54,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 4,
                'cover_image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ভোল্টেজ' => '৩০০০ ভোল্ট ইনস্ট্যান্ট কিলার গ্রিড',
                    'ইউভি ওয়েভলেংথ' => '৩৬৫nm পার্পল লাইট এট্রাক্টর',
                    'ব্যাটারি' => '১২০০ mAh ইউএসবি রিচার্জেবল',
                    'মোড' => 'হ্যান্ডহেল্ড সোয়াটার ও বেস-স্ট্যান্ড ট্র্যাপ মোড',
                ],
            ],
            [
                'id' => 37,
                'title' => 'শাওমি রিচার্জেবল স্মার্ট এলইডি মোশন সেন্সর নাইট লাইট',
                'slug' => 'xiaomi-rechargeable-smart-led-motion-sensor-night-light',
                'type' => 'electronics',
                'category_id' => $catModels['room-care-lifestyle']->id,
                'brand' => 'Xiaomi',
                'model' => 'Mijia Motion Activated Night Light 2',
                'sku' => 'ELC-ROM-05',
                'summary' => 'মানুষের উপস্থিতি শনাক্ত করে স্বয়ংক্রিয়ভাবে জ্বলে ওঠা ম্যাগনেটিক ৩৬০° রোটেটিং নাইট লাইট।',
                'description' => 'সিঁড়ি, আলমারি, করিডোর বা শোবার ঘরের জন্য আদর্শ। অন্ধকার থাকলে এবং মানুষ কাছে এলে স্বয়ংক্রিয়ভাবে চোখ-জুড়ানো ওয়ার্ম লাইট জ্বলে ওঠে এবং ১৫ সেকেন্ড পর নিভে যায়। কোনো তারের প্রয়োজন নেই।',
                'price' => 1350,
                'discount_price' => 1050,
                'stock' => 38,
                'stock_status' => 'in_stock',
                'warranty' => '৬ মাসের অফিসিয়াল রিপ্লেসমেন্ট',
                'badge' => 'নতুন',
                'rating' => 4.9,
                'reviews_count' => 61,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 5,
                'cover_image' => 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সেন্সর' => '১২০° ওয়াইড-এঙ্গেল মোশন ও লাইট সেন্সর',
                    'মাউন্টিং' => 'ম্যাগনেটিক ৩৬০° রোটেশনাল বেস',
                    'লাইটিং' => '২৮০০K সফট ওয়ার্ম কমফোর্ট লাইট',
                    'ব্যাটারি ব্যাকআপ' => 'এক চার্জে ৩৬৫ দিন পর্যন্ত স্ট্যান্ডবাই',
                ],
            ],
        ];

        foreach ($appliances as $item) {
            Product::updateOrCreate(
                ['id' => $item['id']],
                $item
            );
        }

        // Clean up any other electronics items not in this list
        Product::where('type', 'electronics')->whereNotIn('id', array_column($appliances, 'id'))->delete();

        // Deactivate or delete old electronics categories not in the new active list
        $activeCategorySlugs = array_keys($catModels);
        ProductCategory::where('type', 'electronics')->whereNotIn('slug', $activeCategorySlugs)->delete();
    }
}
