<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class HomeApplianceSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Home Appliance Categories
        $categories = [
            [
                'name' => 'কিচেন অ্যাপ্লায়েন্স',
                'slug' => 'kitchen-appliances',
                'type' => 'electronics',
                'description' => 'ব্লেন্ডার, ইলেকট্রিক কেটলি, এয়ার ফ্রায়ার, রাইস কুকার ও আধুনিক রান্নার সামগ্রী',
                'icon' => 'fas fa-blender',
                'sort_order' => 1,
            ],
            [
                'name' => 'হোম ক্লিনিং ও ভ্যাকুয়াম',
                'slug' => 'home-cleaning',
                'type' => 'electronics',
                'description' => 'হ্যান্ডহেল্ড ভ্যাকুয়াম ক্লিনার, ফ্লোর ক্লিনার ও ডাস্ট রিমুভার',
                'icon' => 'fas fa-broom',
                'sort_order' => 2,
            ],
            [
                'name' => 'স্মার্ট হোম ও লাইফস্টাইল',
                'slug' => 'smart-home-lifestyle',
                'type' => 'electronics',
                'description' => 'অটোমেটিক ওয়াটার পাম্প, স্মার্ট সিকিউরিটি ও হোম ইউটিলিটি গ্যাজেট',
                'icon' => 'fas fa-house-laptop',
                'sort_order' => 3,
            ],
            [
                'name' => 'হোম কুলিং ও ফ্যান',
                'slug' => 'home-cooling-fans',
                'type' => 'electronics',
                'description' => 'রিচার্জেবল হোম ও টেবিল ফ্যান, এয়ার সার্কুলেটর ও কুলিং গ্যাজেটস',
                'icon' => 'fas fa-fan',
                'sort_order' => 4,
            ],
            [
                'name' => 'রুম কেয়ার ও হিউমিডিফায়ার',
                'slug' => 'room-care-humidifiers',
                'type' => 'electronics',
                'description' => 'এয়ার হিউমিডিফায়ার, হ্যান্ডহেল্ড স্টিম আয়রন ও অ্যারোমা ডিফিউজার',
                'icon' => 'fas fa-wind',
                'sort_order' => 5,
            ],
            [
                'name' => 'পার্সোনাল কেয়ার অ্যাপ্লায়েন্স',
                'slug' => 'personal-care',
                'type' => 'electronics',
                'description' => 'হেয়ার ড্রায়ার, ট্রিমার ও গ্রুমিং ইলেকট্রনিক্স',
                'icon' => 'fas fa-scissors',
                'sort_order' => 6,
            ],
        ];

        $catModels = [];
        foreach ($categories as $cat) {
            $catModels[$cat['slug']] = ProductCategory::updateOrCreate(
                ['slug' => $cat['slug']],
                $cat
            );
        }

        // Delete test products or old mismatch electronics products
        Product::where('type', 'electronics')->whereIn('id', [15, 16])->delete();

        // 2. Comprehensive Home Appliance Products
        $appliances = [
            [
                'id' => 1,
                'title' => 'শাওমি স্মার্ট মাল্টিফাংশনাল ইলেকট্রিক কেটলি ১.৫ লিটার',
                'slug' => 'xiaomi-smart-electric-kettle-1-5l',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Xiaomi',
                'model' => 'Mijia 1.5L Kettle Pro',
                'sku' => 'HA-KTL-01',
                'summary' => 'দ্রুত পানি গরম করার স্মার্ট অটো-কাট অফ ইলেকট্রিক কেটলি, ফুড-গ্রেড ৩০৪ স্টেইনলেস স্টিল বডি।',
                'description' => 'শাওমির এই ইলেকট্রিক কেটলিটি মাত্র ৪ থেকে ৫ মিনিটে ১.৫ লিটার পানি সম্পূর্ণ ফুটিয়ে তোলে। ডাবল লেয়ার অ্যান্টি-স্ক্যাল্ড ডিজাইন বাইরের বডি ঠান্ডা রাখে। অটোমেটিক পাওয়ার কাট-অফ এবং বয়েল-ড্রাই প্রটেকশন নিশ্চিত করে সর্বোচ্চ নিরাপত্তা।',
                'price' => 2800,
                'discount_price' => 2250,
                'stock' => 45,
                'warranty' => '১ বছরের অফিসিয়াল ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.9,
                'reviews_count' => 52,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1594213114663-ddf3f2a02126?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '১.৫ লিটার',
                    'পাওয়ার' => '১৮০০ ওয়াট',
                    'মেটেরিয়াল' => '৩০৪ ফুড-গ্রেড স্টেইনলেস স্টিল',
                    'সেফটি' => 'অটো শাট-অফ ও ড্রাই-বয়েল প্রটেকশন',
                ],
            ],
            [
                'id' => 2,
                'title' => 'ফিলিপস ডেইলি কালেকশন ৩-ইন-১ ফুড ব্লেন্ডার ও জুসার',
                'slug' => 'philips-daily-collection-3-in-1-blender',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Philips',
                'model' => 'HR2056/00 Daily Collection',
                'sku' => 'HA-BLN-02',
                'summary' => 'মসলা গুঁড়ো, স্মুদি ও ফলের জুস তৈরির শক্তিশালী ৪৫০ ওয়াট মোটরযুক্ত ৩-ইন-১ ব্লেন্ডার।',
                'description' => 'ফিলিপস ৩-ইন-১ ফুড ব্লেন্ডার দৈনন্দিন রান্নার প্রস্তুতি করে তোলে অত্যন্ত সহজ। মজবুত স্টেইনলেস স্টিল ৪-স্টার ব্লেড বরফ ও শক্ত মসলাও মুহূর্তেই গুঁড়ো করে। সহজে পরিষ্কার করার মতো আনব্রেকেবল প্লাস্টিক জার অন্তর্ভুক্ত।',
                'price' => 4900,
                'discount_price' => 3950,
                'stock' => 35,
                'warranty' => '২ বছরের ইন্টারন্যাশনাল ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 64,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মোটর পাওয়ার' => '৪৫০ ওয়াট হাই-টর্ক',
                    'জার সংখ্যা' => '৩টি জার (বড় জুসার, মিডিয়াম চপার, মশলা গ্রাইন্ডার)',
                    'ব্লেড' => 'প্রোব্লেন্ড ৪-স্টার স্টেইনলেস স্টিল',
                    'স্পিড লেভেল' => 'পালস ফাংশনসহ মাল্টি-স্পিড',
                ],
            ],
            [
                'id' => 3,
                'title' => 'শাওমি মিজিয়া স্মার্ট এয়ার ফ্রায়ার ৩.৫ লিটার ডিজিটাল ওভেন',
                'slug' => 'xiaomi-mijia-smart-air-fryer-3-5l',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Xiaomi',
                'model' => 'Mijia Smart 3.5L OLED',
                'sku' => 'HA-AFR-03',
                'summary' => 'তেল ছাড়া স্বাস্থ্যকর ফ্রাই, বেকিং ও গ্রিলিংয়ের জন্য ওলেড ডিসপ্লেযুক্ত স্মার্ট এয়ার ফ্রায়ার।',
                'description' => '৮৫% কম তেলে ক্রিস্পি ও মুখরোচক খাবার তৈরির নির্ভরযোগ্য সমাধান। ওলেড টাচ ডিসপ্লে দিয়ে তাপমাত্রা ও টাইমার নিয়ন্ত্রণ করা যায়। মি হোম অ্যাপের মাধ্যমে ১০০+ প্রি-সেট রেসিপি থেকে সরাসরি রান্না করা সম্ভব।',
                'price' => 8500,
                'discount_price' => 6990,
                'stock' => 20,
                'warranty' => '১ বছরের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 5.0,
                'reviews_count' => 41,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '৩.৫ লিটার নন-স্টিক বাস্কেট',
                    'পাওয়ার' => '১৫০০ ওয়াট ৩৬০° হট এয়ার সার্কুলেশন',
                    'তাপমাত্রা' => '৪০° থেকে ২০০° সেলসিয়াস অ্যাডজাস্টেবল',
                    'কানেক্টিভিটি' => 'Wi-Fi ও Mi Home App সাপোর্ট',
                ],
            ],
            [
                'id' => 4,
                'title' => 'বেসাস রিচার্জেবল হ্যান্ডহেল্ড মিনি ভ্যাকুয়াম ক্লিনার ও ডাস্টার',
                'slug' => 'baseus-rechargeable-mini-handheld-vacuum-cleaner',
                'type' => 'electronics',
                'category_id' => $catModels['home-cleaning']->id,
                'brand' => 'Baseus',
                'model' => 'A2 Pro Cordless Handheld',
                'sku' => 'HA-VAC-04',
                'summary' => 'সোফা, পর্দা, পড়ার টেবিল ও হোম কর্নার পরিষ্কারের শক্তিশালী রিচার্জেবল পোর্টেবল ভ্যাকুয়াম।',
                'description' => 'কর্ডলেস এই মিনি ভ্যাকুয়াম ক্লিনার দিয়ে ঘরের যেকোনো কোণা, সোফা, কিবোর্ড ও বিছানার ধুলোবালি সহজেই পরিষ্কার করা যায়। এতে রয়েছে ওয়াশেবল হেপা ফিল্টার যা ৯৯.৭% সূক্ষ্ম ধুলিকণা আটকে রাখে।',
                'price' => 3200,
                'discount_price' => 2450,
                'stock' => 40,
                'warranty' => '৬ মাসের অফিসিয়াল ওয়ারেন্টি',
                'badge' => 'হট ডিল',
                'rating' => 4.7,
                'reviews_count' => 73,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাকশন পাওয়ার' => '৬০০০ Pa আল্ট্রা-স্ট্রং',
                    'ব্যাটারি' => '৬০০০ mAh রিচার্জেবল লিথিয়াম',
                    'চার্জিং' => 'Type-C ফাস্ট চার্জিং',
                    'ফিল্টার' => 'ওয়াশেবল HEPA ফিল্টারেশন',
                ],
            ],
            [
                'id' => 5,
                'title' => 'ডিয়ারমা হ্যান্ডহেল্ড ফোল্ডেবল জামাকাপড় স্টিম আয়রন',
                'slug' => 'deerma-portable-handheld-garment-steamer',
                'type' => 'electronics',
                'category_id' => $catModels['room-care-humidifiers']->id,
                'brand' => 'Deerma',
                'model' => 'HS007 Foldable Steamer',
                'sku' => 'HA-STM-05',
                'summary' => 'দ্রুত কাপড়ের কুঁচকানো দূর করার ফোল্ডেবল হ্যান্ডহেল্ড হাই-টেম্পারেচার স্টিম আয়রন।',
                'description' => '১০ সেকেন্ডেই প্রস্তুত হওয়া শক্তিশালী স্টিম আয়রন। জামাকাপড় হ্যাঙ্গারে ঝুলিয়ে রেখেই সহজে ইস্ত্রি করা যায়। এর উচ্চ তাপমাত্রার বাষ্প কাপড়ের ৯৯.৯% ব্যাকটেরিয়া ও দুর্গন্ধ দূর করে।',
                'price' => 2800,
                'discount_price' => 2190,
                'stock' => 28,
                'warranty' => '৬ মাসের ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.8,
                'reviews_count' => 45,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাওয়ার' => '৮০০ ওয়াট হাই-প্রেশার স্টিম',
                    'স্টিম স্পিড' => '১০ সেকেন্ডে বাষ্প আউটপুট',
                    'ডিজাইন' => 'ফোল্ডেবল ও ট্রাভেল-ফ্রেন্ডলি',
                    'ওজন' => 'মাত্র ৮০০ গ্রাম',
                ],
            ],
            [
                'id' => 6,
                'title' => 'ডিয়ারমা এফ৬২৮ আল্ট্রাসনিক এয়ার হিউমিডিফায়ার ৫ লিটার',
                'slug' => 'deerma-f628-ultrasonic-air-humidifier-5l',
                'type' => 'electronics',
                'category_id' => $catModels['room-care-humidifiers']->id,
                'brand' => 'Deerma',
                'model' => 'F628 Aroma Ultrasonic 5L',
                'sku' => 'HA-HUM-06',
                'summary' => 'ঘরের আর্দ্রতা বজায় রাখতে এবং এসি রুমের শুষ্কতা দূর করতে আল্ট্রাসনিক কুয়াশা ও অ্যারোমা ডিফিউজার।',
                'description' => '৫ লিটার বড় পানির ট্যাংকের এই হিউমিডিফায়ার টানা ১২ ঘণ্টা নিরবচ্ছিন্ন আর্দ্রতা দেয়। এতে রয়েছে আলাদা অ্যারোমা অয়েল ট্রে, যার সাহায্যে ঘরে সুবাস ছড়ানো যায়। সাইলেন্ট অপারেশন ঘরের ঘুমের কোনো ব্যাঘাত ঘটায় না।',
                'price' => 2900,
                'discount_price' => 2290,
                'stock' => 33,
                'warranty' => '১ বছরের ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.9,
                'reviews_count' => 58,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '৫ লিটার লার্জ ট্যাংক',
                    'ময়েশ্চার আউটপুট' => '৩৫০ মিলি/ঘণ্টা মাইক্রো মিস্ট',
                    'নয়েজ লেভেল' => '৩৫ ডেসিবেলের নিচে আল্ট্রা-সাইলেন্ট',
                    'সুবিধা' => 'এসেনশিয়াল অয়েল ও অ্যারোমা ফ্রেন্ডলি',
                ],
            ],
            [
                'id' => 7,
                'title' => 'বেসাস সাইলেন্ট রিচার্জেবল ফোল্ডেবল ডেস্ক ও হোম ফ্যান',
                'slug' => 'baseus-silent-rechargeable-desk-home-fan',
                'type' => 'electronics',
                'category_id' => $catModels['home-cooling-fans']->id,
                'brand' => 'Baseus',
                'model' => 'Ocean Breeze Silent Fan',
                'sku' => 'HA-FAN-07',
                'summary' => 'লোডশেডিংয়ে টানা ৮-১০ ঘণ্টা শীতল বাতাসের নিশ্চয়তাসহ ইউএসবি রিচার্জেবল পোর্টেবল ফ্যান।',
                'description' => 'ঘরের খাবার টেবিল, বেডসাইড বা বারান্দার জন্য উপযুক্ত শান্ত রিচার্জেবল ফ্যান। ব্রাশলেস মোটরের কারণে কোনো প্রকার শব্দ হয় না। ৪টি উইন্ড স্পিড এবং ১২০ ডিগ্রি অটো অসিলেশন সুবিধা রয়েছে।',
                'price' => 2400,
                'discount_price' => 1850,
                'stock' => 38,
                'warranty' => '৬ মাসের অফিসিয়াল রিপ্লেসমেন্ট',
                'badge' => 'হট ডিল',
                'rating' => 4.8,
                'reviews_count' => 84,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি' => '৪০০০ mAh রিচার্জেবল লিথিয়াম',
                    'ব্যাকআপ টাইম' => '৮ থেকে ১০ ঘণ্টা',
                    'স্পিড মোড' => '৪টি লেভেল অ্যাডজাস্টেবল',
                    'চার্জিং' => 'Type-C USB চার্জিং',
                ],
            ],
            [
                'id' => 8,
                'title' => 'অটোমেটিক ইউএসবি রিচার্জেবল ড্রিংকিং ওয়াটার ডিসপেনসার পাম্প',
                'slug' => 'automatic-usb-drinking-water-dispenser-pump',
                'type' => 'electronics',
                'category_id' => $catModels['smart-home-lifestyle']->id,
                'brand' => 'Idea Smart',
                'model' => 'QuickFlow USB Dispenser',
                'sku' => 'HA-WTR-08',
                'summary' => '২০ লিটার পানির জারে সহজে ফিট হওয়া ওয়ান-টাচ ইলেকট্রিক ওয়াটার ডিসপেনসার পাম্প।',
                'description' => 'ভারী পানির জার তোলার ঝামেলা ছাড়াই ওয়ান-টাচে পানি পান করার আধুনিক ইলেকট্রিক ডিসপেনসার। ফুড-গ্রেড সিলিকন পাইপ এবং স্টেইনলেস স্টিল আউটলেট পানির সম্পূর্ণ বিশুদ্ধতা বজায় রাখে।',
                'price' => 1100,
                'discount_price' => 850,
                'stock' => 50,
                'warranty' => '১ মাসের রিপ্লেসমেন্ট ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.9,
                'reviews_count' => 112,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ব্যাটারি' => '১২০০ mAh রিচার্জেবল',
                    'ব্যাকআপ' => 'এক চার্জে ৫-৬টি ফুল জার',
                    'পাইপ' => 'ফুড-গ্রেড বিপিএ-মুক্ত সিলিকন',
                    'চার্জিং' => 'মাইক্রো ইউএসবি পোর্ট',
                ],
            ],
            [
                'id' => 9,
                'title' => 'প্যানাসনিক ডিজিটাল স্মার্ট অটোমেটিক রাইস কুকার ১.৮ লিটার',
                'slug' => 'panasonic-digital-smart-rice-cooker-1-8l',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Panasonic',
                'model' => 'SR-DF181 Digital Fuzzy Logic',
                'sku' => 'HA-RCK-09',
                'summary' => 'ভাত ঝরঝরে ও গরম রাখার অটো-ওয়ার্ম ফাংশনসহ নন-স্টিক কোটিংযুক্ত ডিজিটাল রাইস কুকার।',
                'description' => 'প্যানাসনিক ডিজিটাল স্মার্ট রাইস কুকার স্বয়ংক্রিয়ভাবে চালের ধরন বুঝে রান্না করে। এতে রয়েছে স্টিমিং বাস্কেট, যার মাধ্যমে ভাত রান্নার পাশাপাশি ডিম, সবজি বা মোমো সহজেই ভাপে সেদ্ধ করা যায়।',
                'price' => 4500,
                'discount_price' => 3750,
                'stock' => 25,
                'warranty' => '১ বছরের ব্র্যান্ড ওয়ারেন্টি',
                'badge' => 'জনপ্রিয়',
                'rating' => 4.9,
                'reviews_count' => 37,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '১.৮ লিটার (১০ কাপ চাল)',
                    'পাওয়ার' => '৭৫০ ওয়াট বিদ্যুৎ সাশ্রয়ী',
                    'ইনার পট' => 'আল্ট্রা নন-স্টিক কোটিং',
                    'মোড' => 'হোয়াইট রাইস, ব্রাউন রাইস, পরিজ ও স্টিম',
                ],
            ],
            [
                'id' => 10,
                'title' => 'মিয়াকে স্মার্ট ইন্ডাকশন ও ইনফ্রারেড কুকার ২২০০ ওয়াট',
                'slug' => 'miyako-smart-induction-cooker-2200w',
                'type' => 'electronics',
                'category_id' => $catModels['kitchen-appliances']->id,
                'brand' => 'Miyako',
                'model' => 'ATC-2200 Smart Touch',
                'sku' => 'HA-IND-10',
                'summary' => 'বিদ্যুৎ সাশ্রয়ী দ্রুত রান্নার জন্য টাচ কন্ট্রোল প্যানেলসহ প্রিমিয়াম ক্রিস্টাল গ্লাস টপ চুলা।',
                'description' => 'গ্যাস সংযোগের ঝামেলা ছাড়াই সব ধরনের রান্নার আধুনিক সমাধান। ৮টি প্রি-সেট কুকিং মোড, চাইল্ড লক ও ৩ ঘণ্টা টাইমার অপশন রয়েছে। যেকোনো মেটাল ও স্টিল পাত্রে সমানভাবে তাপ পৌঁছে দেয়।',
                'price' => 4700,
                'discount_price' => 3890,
                'stock' => 30,
                'warranty' => '১ বছরের সার্ভিস ওয়ারেন্টি',
                'badge' => 'বেস্টসেলার',
                'rating' => 4.8,
                'reviews_count' => 49,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাওয়ার' => '২২০০ ওয়াট হাই এফিশিয়েন্সি',
                    'টপ প্লেট' => 'এ-গ্রেড ব্ল্যাক ক্রিস্টাল গ্লাস',
                    'কন্ট্রোল' => 'ডিজিটাল টাচ ও এলইডি ডিসপ্লে',
                    'সেফটি' => 'চাইল্ড লক ও ওভারহিট প্রটেকশন',
                ],
            ],
        ];

        foreach ($appliances as $item) {
            Product::updateOrCreate(
                ['id' => $item['id']],
                $item
            );
        }

        // Delete any remaining old unused electronics items that are not in this list
        Product::where('type', 'electronics')->whereNotIn('id', array_column($appliances, 'id'))->delete();

        // Delete old unused categories for electronics
        ProductCategory::where('type', 'electronics')->whereNotIn('slug', array_keys($catModels))->delete();
    }
}
