<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class StationeryProductDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Authentic Stationery Categories (আইটেম ভিত্তিক ক্যাটাগরি)
        $categories = [
            [
                'name' => 'খাতা ও নোটবুক',
                'slug' => 'khata-notebooks',
                'type' => 'stationery',
                'description' => 'হার্ডবাউন্ড খাতা, এক্সারসাইজ খাতা, স্পাইরাল নোটবুক ও ড্রয়িং খাতা',
                'icon' => 'fas fa-book-open',
                'sort_order' => 1,
            ],
            [
                'name' => 'রাবার স্ট্যাম্প ও সিলমোহর',
                'slug' => 'rubber-stamps',
                'type' => 'stationery',
                'description' => 'সেলফ-ইনকিং স্ট্যাম্প, কাঠের সিল, ডেট স্ট্যাম্প ও পকেট সিলার',
                'icon' => 'fas fa-stamp',
                'sort_order' => 2,
            ],
            [
                'name' => 'ক্যালেন্ডার ও প্ল্যানার',
                'slug' => 'calendars-planners',
                'type' => 'stationery',
                'description' => 'টেবিল ক্যালেন্ডার, ওয়াল ক্যালেন্ডার, ডায়েরি ও ডেইলি প্ল্যানার',
                'icon' => 'fas fa-calendar-days',
                'sort_order' => 3,
            ],
            [
                'name' => 'ভিজিটিং কার্ড ও বিজনেস কার্ড',
                'slug' => 'visiting-cards',
                'type' => 'stationery',
                'description' => 'ম্যাট ল্যামিনেশন, স্পট ইউভি, গোল্ড ফয়েল ও প্রিমিয়াম ভিজিটিং কার্ড',
                'icon' => 'fas fa-id-card',
                'sort_order' => 4,
            ],
            [
                'name' => 'ক্যাশমেমো ও বিল বই',
                'slug' => 'cash-memo-bills',
                'type' => 'stationery',
                'description' => 'ডুপ্লিকেট ক্যাশমেমো, চালান বই, মানি রিসিট ও ভাউচার বই',
                'icon' => 'fas fa-file-invoice-dollar',
                'sort_order' => 5,
            ],
            [
                'name' => 'সভা রেজিস্টার ও কার্যবিবরণী',
                'slug' => 'meeting-registers',
                'type' => 'stationery',
                'description' => 'রেজুলেশন খাতা, সাধারণ সভা রেজিস্টার ও উপস্থিতি খাতা',
                'icon' => 'fas fa-book-journal-whills',
                'sort_order' => 6,
            ],
            [
                'name' => 'নোটিশ বই ও অফিস রেজিস্টার',
                'slug' => 'notice-books-registers',
                'type' => 'stationery',
                'description' => 'নোটিশ বিতরণ বই, ইনওয়ার্ড/আউটওয়ার্ড ডেসপ্যাচ ও স্টক লেজার',
                'icon' => 'fas fa-clipboard-list',
                'sort_order' => 7,
            ],
            [
                'name' => 'ফাইল, ফোল্ডার ও খাম',
                'slug' => 'files-folders-envelopes',
                'type' => 'stationery',
                'description' => 'বক্স ফাইল, স্প্রিং ক্লিপ ফাইল, লেটারহেড ও অফিস খাম',
                'icon' => 'fas fa-folder-open',
                'sort_order' => 8,
            ],
        ];

        $catModels = [];
        foreach ($categories as $cat) {
            $catModels[$cat['slug']] = ProductCategory::updateOrCreate(
                ['slug' => $cat['slug']],
                $cat
            );
        }

        // Deactivate or remove old obsolete stationery categories
        $activeStatSlugs = array_column($categories, 'slug');
        ProductCategory::where('type', 'stationery')
            ->whereNotIn('slug', $activeStatSlugs)
            ->update(['is_active' => false]);

        // 2. Authentic Stationery Products
        $products = [
            // ─── ১. খাতা ও নোটবুক ───
            [
                'title' => 'আইডিয়া প্রিমিয়াম ১০০ পেজ হার্ডবাউন্ড রুল খাতা',
                'slug' => 'idea-premium-100-page-hardbound-khata',
                'type' => 'stationery',
                'category_id' => $catModels['khata-notebooks']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Standard Hardbound Rule',
                'sku' => 'STN-KHT-01',
                'summary' => 'শক্ত বোর্ড হার্ডকভার এবং ৮০ জিএসএম মসৃণ রুল টানা দীর্ঘস্থায়ী লেখার খাতা।',
                'description' => 'অফিসিয়াল নোট, হিসাবরক্ষণ ও শিক্ষার্থীদের পড়াশোনার জন্য অত্যন্ত মজবুত ও টেকসই খাতা। শক্ত পেস্টবোর্ড বাঁধাই ও উন্নত মানের ৮০ জিএসএম ভার্জিন পাল্প পেপার থাকায় সহজে ছেঁড়ে না এবং কালির কলমে লিখলেও উল্টো পৃষ্ঠায় ছড়ায় না।',
                'price' => 120,
                'discount_price' => 100,
                'stock' => 150,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'বেস্টসেলার',
                'rating' => 4.90,
                'reviews_count' => 54,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => 'ফুলস্কেপ (A5 স্ট্যান্ডার্ড)',
                    'পৃষ্ঠা সংখ্যা' => '১০০ পৃষ্ঠা (৫০ শিট)',
                    'কাগজের মান' => '৮০ GSM ভার্জিন পাল্প পেপার',
                    'কভার' => 'হেভি হার্ডবোর্ড বাঁধাই কভার',
                    'রুল টাইপ' => 'ব্লু রুল টানা ও মার্জিন সহ',
                ],
            ],
            [
                'title' => 'আইডিয়া এক্সিকিউটিভ স্পাইরাল রুল ও প্লেইন নোটবুক (১৬০ পৃষ্ঠা)',
                'slug' => 'idea-executive-spiral-notebook-160-pages',
                'type' => 'stationery',
                'category_id' => $catModels['khata-notebooks']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Executive Wire-O Notebook',
                'sku' => 'STN-KHT-02',
                'summary' => 'মেটাল স্পাইরাল বাউন্ড, ওয়াটারপ্রুফ ম্যাট কভার এবং মসৃণ আইভরি পেপার নোটবুক।',
                'description' => 'দৈনন্দিন মিটিং, প্রাতিষ্ঠানিক নোট ও পরিকল্পনা রচনার জন্য প্রিমিয়াম স্পাইরাল নোট খাতা। ৩৬০ ডিগ্রি সহজে ঘোরানো যায় এবং প্রতিটি পাতা সহজে পাতা উল্টানো যায়। ম্যাট ফ্রস্টেড কভার পানি ও ধুলাবালি থেকে সুরক্ষিত রাখে।',
                'price' => 180,
                'discount_price' => 150,
                'stock' => 120,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'জনপ্রিয়',
                'rating' => 4.85,
                'reviews_count' => 42,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => 'B5 সাইজ (7 x 10 ইঞ্চি)',
                    'পৃষ্ঠা সংখ্যা' => '১৬০ পৃষ্ঠা',
                    'কাগজ' => '৮৫ GSM প্রিমিয়াম আইভরি পেপার',
                    'স্পাইরাল' => 'ডাবল লুপ মেটালিক স্পাইরাল',
                ],
            ],
            [
                'title' => 'আইডিয়া স্কুল ও কলেজ এক্সারসাইজ খাতা (১২০ পেজ - ৬ পিস বান্ডিল)',
                'slug' => 'idea-student-exercise-khata-bundle-6pcs',
                'type' => 'stationery',
                'category_id' => $catModels['khata-notebooks']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Student Value Pack (6in1)',
                'sku' => 'STN-KHT-03',
                'summary' => 'শিক্ষার্থীদের জন্য মার্জিন টানা প্রিমিয়াম কোয়ালিটি এক্সারসাইজ খাতার সাশ্রয়ী বান্ডিল।',
                'description' => 'স্কুল, কলেজ ও মাদ্রাসার শিক্ষার্থীদের ক্লাসনোট ও হোমওয়ার্কের জন্য এক সেটে ৬টি খাতার কম্বো প্যাক। মসৃণ সাদা কাগজ, পরিষ্কার রুল ও স্পষ্ট লাল মার্জিন। হাতের লেখা দ্রুত ও পরিচ্ছন্ন রাখতে সহায়ক।',
                'price' => 360,
                'discount_price' => 290,
                'stock' => 90,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'হট ডিল',
                'rating' => 4.95,
                'reviews_count' => 67,
                'is_featured' => false,
                'cover_image' => 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'বান্ডিল পরিমাণ' => '৬ পিস খাতা এক সাথে',
                    'পৃষ্ঠা প্রতি খাতা' => '১২০ পৃষ্ঠা',
                    'কাগজ' => '৭০ GSM হোয়াইট রাইটিং পেপার',
                    'রুল' => 'মার্জিন সহ বাংলা ও ইংরেজি রুল',
                ],
            ],

            // ─── ২. রাবার স্ট্যাম্প ও সিলমোহর ───
            [
                'title' => 'অফিসিয়াল সেলফ-ইনকিং রাবার স্ট্যাম্প (কাস্টমাইজড নাম ও পদবী)',
                'slug' => 'customized-self-inking-rubber-stamp',
                'type' => 'stationery',
                'category_id' => $catModels['rubber-stamps']->id,
                'brand' => 'Shiny',
                'model' => 'Printer Line S-843',
                'sku' => 'STN-STP-01',
                'summary' => 'স্বয়ংক্রিয় কালির সেলফ-ইনকিং রাবার স্ট্যাম্প। আলাদা প্যাড ছাড়াই ১০,০০০+ স্পষ্ট ছাপ।',
                'description' => 'অফিস, ব্যাংক, হাসপাতাল ও প্রতিষ্ঠানের কর্মকর্তা-কর্মচারীদের নাম, পদবী, মোবাইল ও স্বাক্ষরের জন্য সেরা মানের সেলফ-ইনকিং স্ট্যাম্প। অর্ডার করার পর হোয়াটসঅ্যাপ বা কলে কাস্টমাইজড লেখার টেক্সট গ্রহণ করে নিখুঁতভাবে তৈরি করে দেওয়া হয়।',
                'price' => 350,
                'discount_price' => 280,
                'stock' => 200,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'বেস্টসেলার',
                'rating' => 4.96,
                'reviews_count' => 88,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1589330694653-dad6d3240a2b?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'মেশিন ব্র্যান্ড' => 'Shiny / Trodat অরিজিনাল',
                    'কালি কালার' => 'নীল / কালো / লাল (পছন্দ অনুযায়ী)',
                    'ছাপ সাইজ' => '৩৮ x ১৪ মিমি (৩-৪ লাইন টেক্সট)',
                    'রিফিলযোগ্য' => 'হ্যাঁ, সহজে কালি রিফিল করা যায়',
                ],
            ],
            [
                'title' => 'ক্লাসিক কাঠের হ্যান্ডেল রাবার স্ট্যাম্প (রাউন্ড/ওভাল অফিসিয়াল সিল)',
                'slug' => 'classic-wooden-handle-rubber-stamp-round',
                'type' => 'stationery',
                'category_id' => $catModels['rubber-stamps']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Traditional Wood Mount Seal',
                'sku' => 'STN-STP-02',
                'summary' => 'অফিস, প্রতিষ্ঠান ও লাইব্রেরির জন্য টেকসই পালিশ কাঠের হাতল সহ রাবার সিলমোহর।',
                'description' => 'ঐতিহ্যবাহী কাঠের হাতল বিশিষ্ট গোল সিল ও মনোগ্রাম স্ট্যাম্প। লেজার ভলকানাইজড রাবারে খোদাই করা থাকায় সিলটি অত্যন্ত ধারালো ও পরিষ্কার ছাপ দেয়। সাধারণ স্ট্যাম্প প্যাডে ব্যবহারোপযোগী।',
                'price' => 180,
                'discount_price' => 150,
                'stock' => 150,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'অফিস চয়েস',
                'rating' => 4.88,
                'reviews_count' => 39,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => '৩৫ মিমি থেকে ৪০ মিমি গোল / ডিম্বাকৃতি',
                    'উপাদান' => 'সলিড উড হ্যান্ডেল + হাই-গ্রেড রাবার',
                    'ব্যবহার' => 'অফিসিয়াল গোল সিল, মনোগ্রাম ও অ্যাড্রেস সিল',
                ],
            ],
            [
                'title' => 'রোটেটিং ডাবল কালার তারিখ ও ডেট স্ট্যাম্প মেশিন',
                'slug' => 'rotating-date-stamp-machine-double-color',
                'type' => 'stationery',
                'category_id' => $catModels['rubber-stamps']->id,
                'brand' => 'Trodat',
                'model' => 'Printy Dater 4810',
                'sku' => 'STN-STP-03',
                'summary' => 'তারিখ পরিবর্তনের মেটাল চাকা সহ ডিউরেবল সেলফ-ইনকিং ডেট স্ট্যাম্প মেশিন।',
                'description' => 'বিল, চিঠি ও ফাইলে রিসিভড তারিখ ও নিরীক্ষার সিল দেওয়ার জন্য আদর্শ ডেটার মেশিন। ১০ বছরের তারিখ রেঞ্জ সহ পরিবর্তনযোগ্য রোলার ব্যান্ড। বিল্ট-ইন ইনকপ্যাড থাকায় যেকোনো সময় ঝটপট ব্যবহার করা যায়।',
                'price' => 550,
                'discount_price' => 450,
                'stock' => 75,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'প্রফেশনাল',
                'rating' => 4.92,
                'reviews_count' => 31,
                'is_featured' => false,
                'cover_image' => 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'তারিখ ব্যান্ড' => '১০ বছরের রোটেটিং ক্যালেন্ডার ব্যান্ড',
                    'মেকানিজম' => 'হেভি-ডিউটি মেটাল কোর ও এবিএস শেল',
                    'কালি' => 'সেলফ-ইনকিং ব্লু অ্যান্ড রেড প্যাড',
                ],
            ],

            // ─── ৩. ক্যালেন্ডার ও প্ল্যানার ───
            [
                'title' => 'আইডিয়া প্রিমিয়াম ডেস্ক ক্যালেন্ডার ২০২৬ (টেবিল ক্যালেন্ডার)',
                'slug' => 'idea-premium-desk-calendar-2026',
                'type' => 'stationery',
                'category_id' => $catModels['calendars-planners']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Executive Desk Calendar 2026',
                'sku' => 'STN-CAL-01',
                'summary' => '১২ পাতার রঙিন টেবিল ক্যালেন্ডার। গুরুত্বপূর্ণ সরকারি ছুটি ও সাহিত্যিক কোটেশন সহ।',
                'description' => 'পড়ার টেবিল ও অফিস ডেস্কের সৌন্দর্য বাড়িয়ে তুলতে চার কালারের দৃষ্টিনন্দন এক্সিকিউটিভ ডেস্ক ক্যালেন্ডার। ৩০০ জিএসএম আর্ট কার্ডে গ্লস ফিনিশিং, শক্ত হার্ডবোর্ড মাউন্ট স্ট্যান্ড এবং ডাবল ওয়্যার মেটাল স্পাইরাল। প্রতিটি পাতায় দিন গণনা ও নোট স্পেস রয়েছে।',
                'price' => 250,
                'discount_price' => 200,
                'stock' => 180,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'নতুন ২০২৬',
                'rating' => 4.98,
                'reviews_count' => 62,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাতা সংখ্যা' => '১২ পাতা + ১ কভার পেজ',
                    'কাগজ' => '৩০০ GSM আর্ট কার্ড (গ্লস ফিনিশ)',
                    'স্ট্যান্ড' => 'ভারী মাউন্টিং হার্ডবোর্ড ত্রিভুজ স্ট্যান্ড',
                    'ক্যালেন্ডার বছর' => '২০২৬ (বাংলা, ইংরেজি ও হিজরি সন)',
                ],
            ],
            [
                'title' => 'বাৎসরিক ওয়াল ক্যালেন্ডার ২০২৬ (৬ পাতা প্রিমিয়াম আর্ট পেপার)',
                'slug' => 'yearly-wall-calendar-2026-art-paper',
                'type' => 'stationery',
                'category_id' => $catModels['calendars-planners']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Heritage Wall Calendar (6-Sheet)',
                'sku' => 'STN-CAL-02',
                'summary' => 'দেয়ালে ঝুলানোর জন্য দৃষ্টিনন্দন ৬ পাতা আর্ট পেপার বাৎসরিক দেয়াল ক্যালেন্ডার।',
                'description' => 'গৃহকোণ, পাঠাগার ও প্রতিষ্ঠানের দেয়ালে টানানোর উপযোগী বৃহদাকার ৬ পাতার ক্যালেন্ডার। প্রতি পাতায় দুই মাসের তারিখ, পূর্ণিমা-অমাবস্যা ও ছুটির তালিকা। মেটালিক টিন হ্যাঙ্গার দিয়ে সহজেই দেয়ালে টানানো যায়।',
                'price' => 180,
                'discount_price' => 150,
                'stock' => 160,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'জনপ্রিয়',
                'rating' => 4.86,
                'reviews_count' => 44,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => '১৫ x ২০ ইঞ্চি',
                    'পাতা' => '৬ পাতা আর্ট পেপার (১৭০ GSM)',
                    'ঝুলানোর ব্যবস্থা' => 'মেটাল টিন ক্ল্যাম্প উইথ হ্যাঙ্গার',
                ],
            ],
            [
                'title' => 'ডেইলি টাস্ক প্ল্যানার ও এক্সিকিউটিভ টেবিল প্যাড (৫০ শিট)',
                'slug' => 'daily-task-planner-table-pad-50sheets',
                'type' => 'stationery',
                'category_id' => $catModels['calendars-planners']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Daily Productivity Notepad',
                'sku' => 'STN-CAL-03',
                'summary' => 'দৈনন্দিন কাজের অগ্রাধিকার, মিটিংয়ের সময়সূচি ও নোট লেখার টিয়ার-অফ টেবিল প্যাড।',
                'description' => 'ব্যস্ত কর্মদিবসে প্রতিটি কাজ সময়মতো শেষ করার জন্য আদর্শ ওয়ার্কস্টেশন প্ল্যানার প্যাড। ১০০ জিএসএম প্রিমিয়াম কাগজে মুদ্রিত। কাজ শেষ হলে টিক চিহ্ন দিন এবং দিন শেষে পৃষ্ঠাটি সহজেই ছিঁড়ে ফেলুন।',
                'price' => 220,
                'discount_price' => 170,
                'stock' => 95,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'উৎপাদনশীলতা',
                'rating' => 4.90,
                'reviews_count' => 38,
                'is_featured' => false,
                'cover_image' => 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => 'A5 সাইজ (৮.৩ x ৫.৮ ইঞ্চি)',
                    'শিট সংখ্যা' => '৫০ শিট টিয়ার-অফ প্যাড',
                    'কাগজ' => '১০০ GSM ফাউন্টেন পেন ফ্রেন্ডলি পেপার',
                    'সেকশন' => 'টপ প্রায়োরিটি, টু-ডু লিস্ট, নোটিশ ও মেমো',
                ],
            ],

            // ─── ৪. ভিজিটিং কার্ড ও বিজনেস কার্ড ───
            [
                'title' => 'ম্যাট ল্যামিনেশন প্রিমিয়াম ভিজিটিং কার্ড (১০০ পিস বক্স)',
                'slug' => 'matte-lamination-visiting-cards-100pcs',
                'type' => 'stationery',
                'category_id' => $catModels['visiting-cards']->id,
                'brand' => 'আইডিয়া প্রিন্টস',
                'model' => 'Matte Laminated Business Card (100pcs)',
                'sku' => 'STN-CRD-01',
                'summary' => '৩০০ জিএসএম আর্ট কার্ডে উভয় পাশ চার কালার প্রিন্ট ও প্রিমিয়াম ওয়াটারপ্রুফ ম্যাট কোটিং।',
                'description' => 'পেশাজীবী, ব্যবসায়ী ও লেখকদের আত্মপরিচয় ফুটিয়ে তুলতে প্রিমিয়াম ভিজিটিং কার্ড। ৩০০ জিএসএম আর্ট কার্ডে আধুনিক ডিজিটাল/অফসেট প্রিন্ট এবং মসৃণ ম্যাট ফিনিশ। কার্ড পানি ও ঘাম থেকে সুরক্ষিত থাকে। অ্যাক্রিলিক ট্রান্সপারেন্ট বক্সে সরবরাহ করা হয়।',
                'price' => 350,
                'discount_price' => 280,
                'stock' => 300,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'বেস্টসেলার',
                'rating' => 4.95,
                'reviews_count' => 95,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পরিমাণ' => '১০০ পিস এক বক্সে',
                    'কাগজের মান' => '৩০০ GSM আর্ট কার্ড',
                    'প্রিন্টিং' => 'উভয় পাশ ফুল কালার HD প্রিন্ট',
                    'কোটিং' => 'ডাবল সাইড ম্যাট লেমিনেশন',
                    'সাইজ' => '৩.২৫ x ২.০ ইঞ্চি (স্ট্যান্ডার্ড)',
                ],
            ],
            [
                'title' => 'লাক্সারি স্পট ইউভি ও এমবসড ভিজিটিং কার্ড (১০০ পিস)',
                'slug' => 'luxury-spot-uv-visiting-cards-100pcs',
                'type' => 'stationery',
                'category_id' => $catModels['visiting-cards']->id,
                'brand' => 'আইডিয়া প্রিন্টস',
                'model' => 'Spot UV Elite Business Card',
                'sku' => 'STN-CRD-02',
                'summary' => 'লোগো ও নামে স্পট গ্লস গ্লেজি ইফেক্ট সহ আকর্ষণীয় এক্সিকিউটিভ বিজনেস কার্ড।',
                'description' => 'কর্পোরেট নির্বাহীদের জন্য আভিজাত্যের প্রতীক স্পট ইউভি বিজনেস কার্ড। ম্যাট ব্যাকগ্রাউন্ডের উপর লোগো ও মূল লেখার অংশে স্পট গ্লস কোটিং থাকায় আলো পড়লে উজ্জ্বল হয়ে ওঠে এবং হাতের ছোঁয়ায় টেক্সচার অনুধাবন করা যায়।',
                'price' => 650,
                'discount_price' => 520,
                'stock' => 150,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'প্রিমিয়াম',
                'rating' => 4.97,
                'reviews_count' => 48,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'কাগজ' => '৩৫০ GSM হেভি ডিউটি বোর্ড',
                    'স্পেশাল ইফেক্ট' => 'ম্যাট লেমিনেশন + নির্বাচিত অংশে স্পট ইউভি গ্লস',
                    'পরিমাণ' => '১০০ পিস প্রিমিয়াম প্যাক',
                ],
            ],
            [
                'title' => 'প্রিমিয়াম গোল্ডেন ফয়েল ও টেক্সচার্ড বিজনেস কার্ড (১০০ পিস)',
                'slug' => 'golden-foil-textured-business-cards-100pcs',
                'type' => 'stationery',
                'category_id' => $catModels['visiting-cards']->id,
                'brand' => 'আইডিয়া প্রিন্টস',
                'model' => 'Royal Gold Foil Letterpress Card',
                'sku' => 'STN-CRD-03',
                'summary' => 'ইম্পোর্টেড লিনেন টেক্সচার্ড পেপারে গোল্ডেন ফয়েল স্ট্যাম্পিং করা এক্সক্লুসিভ বিজনেস কার্ড।',
                'description' => 'অভিজাত ও রাজকীয় চেহারার জন্য টেক্সচার্ড আর্ট পেপারের উপর সোনালী মেটালিক ফয়েল হট স্ট্যাম্পিং। ক্লাসিক রুচি ও পেশাদার ভাবমূর্তি প্রকাশের সেরা মাধ্যম।',
                'price' => 850,
                'discount_price' => 700,
                'stock' => 100,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'এক্সক্লুসিভ',
                'rating' => 4.96,
                'reviews_count' => 36,
                'is_featured' => false,
                'cover_image' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'কাগজ' => '৩০০ GSM ইম্পোর্টেড লিনেন টেক্সচার পেপার',
                    'ফয়েলিং' => 'মেটালিক গোল্ড ফয়েল হট স্ট্যাম্পিং',
                    'পরিমাণ' => '১০০ পিস কাঠের/হার্ডবোর্ড বক্সে',
                ],
            ],

            // ─── ৫. ক্যাশমেমো ও বিল বই ───
            [
                'title' => 'ডুপ্লিকেট ক্যাশমেমো ও ইনভয়েস বই (১+১ কার্বনলেস - ৫০ সেট)',
                'slug' => 'duplicate-carbonless-cash-memo-50sets',
                'type' => 'stationery',
                'category_id' => $catModels['cash-memo-bills']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'NCR Duplicate Invoice Book (50 Sets)',
                'sku' => 'STN-CSH-01',
                'summary' => 'স্বয়ংক্রিয় কার্বনলেস (NCR) ডুপ্লিকেট ক্যাশমেমো বই। কার্বন পেপার ছাড়াই নিচের কপিতে নিখুঁত ছাপ।',
                'description' => 'দোকান, শোরুম ও ব্যবসায়িক প্রতিষ্ঠানের বিক্রয় রসিদ ও ইনভয়েস লেখার জন্য প্রিমিয়াম ডুপ্লিকেট ক্যাশমেমো বই। আলাদা কোনো কালো কার্বন পেপার রাখার ঝামেলা নেই; ওপরের কপিতে লিখলেই নিখুঁতভাবে নিচের রঙিন কপিতে লেখা উঠে যায়। মাইক্রো পারফোরেশনে সহজে পাতা ছেঁড়া যায়।',
                'price' => 160,
                'discount_price' => 130,
                'stock' => 250,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'বেস্টসেলার',
                'rating' => 4.92,
                'reviews_count' => 76,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => '১/১৬ সাইজ (৮ x ৫ ইঞ্চি)',
                    'সেট সংখ্যা' => '৫০ সেট (মোট ১০০ পাতা)',
                    'কাগজ' => 'উন্নত সেলফ-কার্বনলেস NCR পেপার',
                    'সিরিয়াল' => 'লাল কালির প্রমিত ক্রমিক নম্বর প্রিন্ট',
                ],
            ],
            [
                'title' => 'ট্রিপ্লিকেট বিল ও চালান বই (১+২ কার্বনলেস - ৫০ সেট)',
                'slug' => 'triplicate-bill-chalan-book-50sets',
                'type' => 'stationery',
                'category_id' => $catModels['cash-memo-bills']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Triplicate Delivery Chalan Book',
                'sku' => 'STN-CSH-02',
                'summary' => 'শোরুম ও গুদামের মাল ডেলিভারি চালানের জন্য ৩ কপি (কাস্টমার, অ্যাকাউন্টস ও গেট পাস) চালান বই।',
                'description' => 'প্রতি লেনদেনে ৩টি পৃথক রঙিন কপি তৈরি হয়: মূল সাদা কপি ক্রেতার জন্য, গোলাপি কপি অ্যাকাউন্টসের জন্য এবং হলুদ কপি ডেলিভারি গেটের জন্য। মজবুত বোর্ড বাইন্ডিং এবং স্পষ্ট কলাম প্রিন্ট।',
                'price' => 220,
                'discount_price' => 180,
                'stock' => 180,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'অফিস চয়েস',
                'rating' => 4.89,
                'reviews_count' => 41,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সেট সংখ্যা' => '৫০ সেট (১৫০ পাতা)',
                    'কপি' => '১টি মূল সাদা কপি + ২টি রঙিন NCR কপি',
                    'পারফোরেশন' => 'সহজে ছেঁড়ার জন্য মাইক্রো-কাটিং',
                ],
            ],
            [
                'title' => 'অফিসিয়াল মানি রিসিট ও জমা রশিদ বই (১০০ পেজ কাউন্টারফয়েল)',
                'slug' => 'official-money-receipt-book-100pages',
                'type' => 'stationery',
                'category_id' => $catModels['cash-memo-bills']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Money Receipt Book with Counterfoil',
                'sku' => 'STN-CSH-03',
                'summary' => 'টাকা গ্রহণ ও অফিসিয়াল লেনদেনের জন্য কাউন্টারফয়েল সহ মানি রিসিট বই।',
                'description' => 'টাকা প্রাপ্তির রসিদ গ্রাহককে দেওয়ার পর প্রমাণস্বরূপ বামপাশের কাউন্টারফয়েল বা মুড়ি বইয়ে সংরক্ষিত থাকে। স্কুল, কলেজ, মাদ্রাসা, ক্লাব ও বাণিজ্যিক অফিসের জন্য নির্ভরযোগ্য হিসাবরক্ষণ রশিদ।',
                'price' => 140,
                'discount_price' => 110,
                'stock' => 200,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'জনপ্রিয়',
                'rating' => 4.90,
                'reviews_count' => 52,
                'is_featured' => false,
                'cover_image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পাতা সংখ্যা' => '১০০টি রিসিট পাতা',
                    'বৈশিষ্ট্য' => 'কাউন্টারফয়েল ও পারফোরেটেড রিসিট স্লিপ',
                    'কাগজ' => '৭০ GSM হোয়াইট লেজার পেপার',
                ],
            ],

            // ─── ৬. সভা রেজিস্টার ও কার্যবিবরণী ───
            [
                'title' => 'সভা কার্যবিবরণী ও রেজুলেশন রেজিস্টার বই (২০০ পেজ হার্ডবাউন্ড)',
                'slug' => 'meeting-resolution-register-book-200pages',
                'type' => 'stationery',
                'category_id' => $catModels['meeting-registers']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Official Meeting Resolution Register',
                'sku' => 'STN-REG-01',
                'summary' => 'সভা, সমিতি ও পরিচালনা পর্ষদের সিদ্ধান্ত লিপিবদ্ধ করে স্থায়ী সংরক্ষণের জন্য লেজার খাতা।',
                'description' => 'যেকোনো সভা, ক্লাব, সমবায় সমিতি, ম্যানেজিং কমিটি বা পরিচালনা পর্ষদের সভার রেজুলেশন ও কার্যবিবরণী লেখার জন্য প্রমিত হার্ডবাউন্ড খাতা। ৮০ জিএসএম দীর্ঘস্থায়ী ব্লু লেজার পেপারে তৈরি, যা বছরের পর বছর সংরক্ষণ করলেও কাগজ হলুদ বা নষ্ট হয় না।',
                'price' => 320,
                'discount_price' => 260,
                'stock' => 140,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'বেস্টসেলার',
                'rating' => 4.96,
                'reviews_count' => 63,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => 'ফুলস্কেপ (১৩ x ৮.৫ ইঞ্চি)',
                    'পৃষ্ঠা সংখ্যা' => '২০০ পৃষ্ঠা',
                    'কাগজের মান' => '৮০ GSM ব্লু লেজার রেজিস্টার পেপার',
                    'বাঁধাই' => 'রেক্সিন লেদার কোটেড হেভি হার্ডবোর্ড বাঁধাই',
                    'রুল' => 'স্পষ্ট মার্জিন ও পৃষ্ঠা নম্বর প্রিন্ট',
                ],
            ],
            [
                'title' => 'সাধারণ সভা ও পরিচালনা পর্ষদ রেজিস্টার বই (৩০০ পৃষ্ঠা)',
                'slug' => 'general-meeting-board-register-300pages',
                'type' => 'stationery',
                'category_id' => $catModels['meeting-registers']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Deluxe Board Meeting Register (300P)',
                'sku' => 'STN-REG-02',
                'summary' => 'কর্পোরেট প্রতিষ্ঠান, সমবায় ও সংগঠনের জন্য সোনালী ফয়েল কভার বিশিষ্ট ৩০০ পৃষ্ঠার রেজিস্টার।',
                'description' => 'বার্ষিক সাধারণ সভা (AGM), বিশেষ সাধারণ সভা ও নির্বাহী কমিটির সভা লিপিবদ্ধ করার জন্য ৩০০ পৃষ্ঠার বৃহৎ রেজিস্টার। শক্ত সুতা দিয়ে সেলাই করা এবং আকর্ষণীয় গোল্ডেন ফয়েল এমবসড কভার।',
                'price' => 450,
                'discount_price' => 370,
                'stock' => 90,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'প্রিমিয়াম',
                'rating' => 4.94,
                'reviews_count' => 37,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পৃষ্ঠা' => '৩০০ পৃষ্ঠা (বৃহৎ ধারণক্ষমতা)',
                    'বাইন্ডিং' => 'সুতা সেলাই ও পেস্ট বোর্ড লেদার কভার',
                    'কাগজ' => '৮৫ GSM হেভি ডিউটি লেজার পেপার',
                ],
            ],
            [
                'title' => 'সদস্য হাজিরা ও মিটিং উপস্থিতি খাতা (১০০ পেজ কলাম প্রিন্ট)',
                'slug' => 'meeting-attendance-register-100pages',
                'type' => 'stationery',
                'category_id' => $catModels['meeting-registers']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Member Attendance & Signature Register',
                'sku' => 'STN-REG-03',
                'summary' => 'মিটিংয়ে উপস্থিত সদস্যদের ক্রমিক, নাম, পদবী ও স্বাক্ষরের সুনির্দিষ্ট কলাম সহ উপস্থিতি খাতা।',
                'description' => 'যেকোনো আনুষ্ঠানিক মিটিংয়ে অংশগ্রহণকারী সদস্যদের স্বাক্ষর গ্রহণের জন্য তৈরি প্রমিত খাতা। পূর্বনির্ধারিত ছকে সদস্যদের নাম, পদবী, মোবাইল নম্বর, আগমনের সময় ও স্বাক্ষরের ঘর বিন্যস্ত থাকায় পরিচালনা অত্যন্ত সহজ হয়।',
                'price' => 180,
                'discount_price' => 150,
                'stock' => 120,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'জনপ্রিয়',
                'rating' => 4.88,
                'reviews_count' => 29,
                'is_featured' => false,
                'cover_image' => 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পৃষ্ঠা সংখ্যা' => '১০০ পৃষ্ঠা',
                    'ফরম্যাট' => 'নাম, পদবী, মোবাইল, স্বাক্ষর ও মন্তব্য কলাম',
                    'কভার' => 'পেস্টবোর্ড ও কালার লেমিনেটেড কভার',
                ],
            ],

            // ─── ৭. নোটিশ বই ও অফিস রেজিস্টার ───
            [
                'title' => 'অফিসিয়াল নোটিশ বিতরণ ও স্বাক্ষর বই (২০০ পৃষ্ঠা হার্ডকভার)',
                'slug' => 'official-notice-distribution-book-200pages',
                'type' => 'stationery',
                'category_id' => $catModels['notice-books-registers']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Notice Dispatch & Peon Book',
                'sku' => 'STN-NTC-01',
                'summary' => 'নোটিশ জারি, প্রাপ্তিস্বীকার ও স্বাক্ষর গ্রহণের জন্য সুনির্দিষ্ট কলাম বিশিষ্ট অফিস নোটিশ বই।',
                'description' => 'অফিসিয়াল আদেশ, জরুরি নোটিশ ও সার্কুলার বিতরণ করে রিসিভিং স্বাক্ষর নেওয়ার খাতা (পিয়ন বুক)। প্রতিটি নোটিশের স্মারক নম্বর, বিষয়, প্রাপকের নাম, বিতরণের তারিখ ও রিসিভিং কর্মকর্তার পূর্ণাঙ্গ স্বাক্ষরের ঘর মুদ্রিত রয়েছে।',
                'price' => 250,
                'discount_price' => 200,
                'stock' => 130,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'অফিস মাস্ট-হ্যাভ',
                'rating' => 4.93,
                'reviews_count' => 58,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => 'ফুলস্কেপ সাইজ',
                    'পৃষ্ঠা' => '২০০ পৃষ্ঠা',
                    'কলাম' => 'স্মারক নং, নোটিশ বিষয়, প্রাপকের নাম ও স্বাক্ষর',
                    'বাঁধাই' => 'হার্ডবোর্ড রেক্সিন স্পাইন বাঁধাই',
                ],
            ],
            [
                'title' => 'চিঠি আদান-প্রদান (ইনওয়ার্ড / আউটওয়ার্ড) ডেসপ্যাচ রেজিস্টার',
                'slug' => 'inward-outward-dispatch-register-book',
                'type' => 'stationery',
                'category_id' => $catModels['notice-books-registers']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Inward / Outward Dispatch Ledger',
                'sku' => 'STN-NTC-02',
                'summary' => 'সরকারি, বেসরকারি ও শিক্ষাপ্রতিষ্ঠানের দৈনন্দিন ডাক ও চিঠি রেকর্ডের ইনওয়ার্ড-আউটওয়ার্ড খাতা।',
                'description' => 'প্রতিষ্ঠানে আসা প্রতিটি চিঠি এবং প্রেরিত প্রতিটি চিঠির রেকর্ড সুশৃঙ্খলভাবে সংরক্ষণের জন্য আদর্শ ডেসপ্যাচ রেজিস্টার। প্রেরক, প্রাপক, ট্র্যাকিং নম্বর ও তারিখের স্পষ্ট কলাম ফরম্যাট।',
                'price' => 300,
                'discount_price' => 240,
                'stock' => 110,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'জনপ্রিয়',
                'rating' => 4.91,
                'reviews_count' => 35,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'সাইজ' => 'ফুলস্কেপ চওড়া কলাম সাইজ',
                    'পৃষ্ঠা' => '২০০ পৃষ্ঠা',
                    'কাগজ' => '৮০ GSM অ্যাজুর লেজার পেপার',
                ],
            ],
            [
                'title' => 'স্টক ও ইনভেন্টরি লেজার রেজিস্টার খাতা (২০০ পেজ)',
                'slug' => 'stock-inventory-ledger-register-200pages',
                'type' => 'stationery',
                'category_id' => $catModels['notice-books-registers']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Material Stock Ledger Register',
                'sku' => 'STN-NTC-03',
                'summary' => 'পণ্য ও কাঁচামাল গ্রহণ, ইস্যু ও বর্তমান মজুদ সংরক্ষণের নির্ভরযোগ্য স্টক রেজিস্টার বুক।',
                'description' => 'গুদাম ও অফিসের আসবাবপত্র, যন্ত্রপাতি ও স্টেশনারি দ্রব্যের হিসাব সংরক্ষণের জন্য তিন কলাম বিশিষ্ট স্টক খাতা (আগত, নির্গত ও উদ্বৃত্ত)।',
                'price' => 280,
                'discount_price' => 220,
                'stock' => 100,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'প্রফেশনাল',
                'rating' => 4.89,
                'reviews_count' => 28,
                'is_featured' => false,
                'cover_image' => 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পৃষ্ঠা' => '২০০ পৃষ্ঠা',
                    'ফরম্যাট' => 'তারিখ, চালান নং, প্রাপ্ত পরিমাণ, বিতরিত পরিমাণ ও ব্যালেন্স',
                    'কাগজ' => '৮০ GSM স্মুথ রাইটিং পেপার',
                ],
            ],

            // ─── ৮. ফাইল, ফোল্ডার ও খাম ───
            [
                'title' => 'আইডিয়া হেভি ডিউটি বক্স ফাইল (লিভার আর্চ মেকানিজম)',
                'slug' => 'idea-heavy-duty-box-file-lever-arch',
                'type' => 'stationery',
                'category_id' => $catModels['files-folders-envelopes']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Lever Arch Heavy Box File',
                'sku' => 'STN-FIL-01',
                'summary' => 'শক্ত পিভিসি কোটিং বোর্ড, মেটাল এজ প্রটেকশন এবং ডিউরেবল লিভার আর্চ পেপার ক্ল্যাম্প।',
                'description' => 'গুরুত্বপূর্ণ দলিল, ভাউচার ও নথি সাজিয়ে রাখার জন্য দীর্ঘস্থায়ী বক্স ফাইল। ক্রোমিয়াম প্লেটেড শক্তিশালী লিভার আর্চ লক ৫০০-এর বেশি কাগজ শক্তভাবে ধরে রাখে। ফাইলে সহজে সনাক্ত করতে ব্যাক স্পাইনে লেবেল স্লট রয়েছে।',
                'price' => 180,
                'discount_price' => 150,
                'stock' => 200,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'বেস্টসেলার',
                'rating' => 4.90,
                'reviews_count' => 84,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'ক্যাপাসিটি' => '৫০০+ পৃষ্ঠা ডকুমেন্ট ধারণক্ষমতা',
                    'মেকানিজম' => 'প্রিমিয়াম লিভার আর্চ রিং মেকানিজম',
                    'কভার' => 'ওয়াটার রেজিস্ট্যান্ট পিভিসি কোটিং ও মেটাল কর্নার',
                ],
            ],
            [
                'title' => 'অফিসিয়াল লেটারহেড প্যাড ও ডিআইএল খাম (৫০ সেট)',
                'slug' => 'official-letterhead-pad-envelope-set-50sets',
                'type' => 'stationery',
                'category_id' => $catModels['files-folders-envelopes']->id,
                'brand' => 'আইডিয়া প্রিন্টস',
                'model' => 'Executive Corporate Letterhead & Envelope',
                'sku' => 'STN-FIL-02',
                'summary' => '১০০ জিএসএম এক্সিকিউটিভ বন্ড পেপারে লোগো প্রিন্টেড লেটারহেড ও সেলফ-অ্যাডেসিভ খাম সেট।',
                'description' => 'কর্পোরেট চিঠিপত্র, প্রশংসাপত্র ও অফিসিয়াল চুক্তির জন্য প্রিমিয়াম লেটারহেড প্যাড ও ম্যাচিং উইন্ডো/নন-উইন্ডো খাম। ইঙ্কজেট ও লেজার প্রিন্টারে অনায়াসে প্রিন্ট করা যায়।',
                'price' => 450,
                'discount_price' => 350,
                'stock' => 120,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'অফিস চয়েস',
                'rating' => 4.95,
                'reviews_count' => 46,
                'is_featured' => true,
                'cover_image' => 'https://images.unsplash.com/photo-1583521214690-73421a1829a9?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'লেটারহেড' => '৫০ শিট A4 সাইজ (১০০ GSM রয়্যাল বন্ড পেপার)',
                    'খাম' => '৫০ পিস সেলফ-অ্যাডেসিভ পিল অ্যান্ড সিল খাম',
                ],
            ],
            [
                'title' => 'ক্লিপ ফাইল ও প্রেজেন্টেশন ফোল্ডার (৫ পিস প্যাক)',
                'slug' => 'clip-file-presentation-folder-pack-5pcs',
                'type' => 'stationery',
                'category_id' => $catModels['files-folders-envelopes']->id,
                'brand' => 'আইডিয়া প্রকাশন',
                'model' => 'Quick Spring Clip File (Pack of 5)',
                'sku' => 'STN-FIL-03',
                'summary' => 'অফিসিয়াল রিপোর্ট ও প্রেজেন্টেশনের জন্য শক্ত স্প্রিং ক্লিপ ফোল্ডার। পাঞ্চিং ছাড়াই ফাইল করা যায়।',
                'description' => 'কাগজে ফুটো বা ছিদ্র না করেই ৩০-৪০ পৃষ্ঠা অনায়াসে আটকে রাখার সাইড ক্লিপ ফোল্ডার। স্বচ্ছ কভার থাকায় ভেতরের প্রথম পাতা সহজেই দেখা যায়। ৫টি রঙের ৫টি ফাইলের আকর্ষণীয় সেট।',
                'price' => 250,
                'discount_price' => 200,
                'stock' => 160,
                'stock_status' => 'in_stock',
                'warranty' => null,
                'badge' => 'জনপ্রিয়',
                'rating' => 4.87,
                'reviews_count' => 33,
                'is_featured' => false,
                'cover_image' => 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&auto=format&fit=crop&q=80',
                'specifications' => [
                    'পরিমাণ' => '৫ পিস ফোল্ডার সেট',
                    'মেটিরিয়াল' => 'ফ্লেক্সিবল ও স্ক্র্যাচ-প্রুফ পলিপ্রপিলিন',
                    'ক্লিপ' => 'স্টেইনলেস স্টিল প্রেসার ক্লিপ',
                ],
            ],
        ];

        // Clean out old obsolete stationery products to ensure clean catalog
        $newProductSlugs = array_column($products, 'slug');
        Product::where('type', 'stationery')
            ->whereNotIn('slug', $newProductSlugs)
            ->delete();

        // Seed or update products
        foreach ($products as $idx => $prod) {
            $prod['sort_order'] = $idx + 1;
            Product::updateOrCreate(
                ['slug' => $prod['slug']],
                $prod
            );
        }
    }
}
