@php
    $selectedCode = $selected ?? old('country_code', '+880');
    $countryList = [
        ['code' => '+880', 'flag' => '🇧🇩', 'name' => 'Bangladesh (+880)', 'short' => 'BD'],
        ['code' => '+91',  'flag' => '🇮🇳', 'name' => 'India (+91)', 'short' => 'IN'],
        ['code' => '+966', 'flag' => '🇸🇦', 'name' => 'Saudi Arabia (+966)', 'short' => 'SA'],
        ['code' => '+971', 'flag' => '🇦🇪', 'name' => 'UAE (+971)', 'short' => 'AE'],
        ['code' => '+974', 'flag' => '🇶🇦', 'name' => 'Qatar (+974)', 'short' => 'QA'],
        ['code' => '+965', 'flag' => '🇰🇼', 'name' => 'Kuwait (+965)', 'short' => 'KW'],
        ['code' => '+968', 'flag' => '🇴🇲', 'name' => 'Oman (+968)', 'short' => 'OM'],
        ['code' => '+973', 'flag' => '🇧🇭', 'name' => 'Bahrain (+973)', 'short' => 'BH'],
        ['code' => '+60',  'flag' => '🇲🇾', 'name' => 'Malaysia (+60)', 'short' => 'MY'],
        ['code' => '+65',  'flag' => '🇸🇬', 'name' => 'Singapore (+65)', 'short' => 'SG'],
        ['code' => '+1',   'flag' => '🇺🇸', 'name' => 'USA / Canada (+1)', 'short' => 'US/CA'],
        ['code' => '+44',  'flag' => '🇬🇧', 'name' => 'UK (+44)', 'short' => 'UK'],
        ['code' => '+61',  'flag' => '🇦🇺', 'name' => 'Australia (+61)', 'short' => 'AU'],
        ['code' => '+39',  'flag' => '🇮🇹', 'name' => 'Italy (+39)', 'short' => 'IT'],
        ['code' => '+49',  'flag' => '🇩🇪', 'name' => 'Germany (+49)', 'short' => 'DE'],
        ['code' => '+33',  'flag' => '🇫🇷', 'name' => 'France (+33)', 'short' => 'FR'],
        ['code' => '+81',  'flag' => '🇯🇵', 'name' => 'Japan (+81)', 'short' => 'JP'],
        ['code' => '+82',  'flag' => '🇰🇷', 'name' => 'South Korea (+82)', 'short' => 'KR'],
        ['code' => '+92',  'flag' => '🇵🇰', 'name' => 'Pakistan (+92)', 'short' => 'PK'],
        ['code' => '+977', 'flag' => '🇳🇵', 'name' => 'Nepal (+977)', 'short' => 'NP'],
        ['code' => '+94',  'flag' => '🇱🇰', 'name' => 'Sri Lanka (+94)', 'short' => 'LK'],
        ['code' => '+960', 'flag' => '🇲🇻', 'name' => 'Maldives (+960)', 'short' => 'MV'],
        ['code' => '+975', 'flag' => '🇧🇹', 'name' => 'Bhutan (+975)', 'short' => 'BT'],
        ['code' => '+66',  'flag' => '🇹🇭', 'name' => 'Thailand (+66)', 'short' => 'TH'],
        ['code' => '+62',  'flag' => '🇮🇩', 'name' => 'Indonesia (+62)', 'short' => 'ID'],
        ['code' => '+90',  'flag' => '🇹🇷', 'name' => 'Turkey (+90)', 'short' => 'TR'],
        ['code' => '+20',  'flag' => '🇪🇬', 'name' => 'Egypt (+20)', 'short' => 'EG'],
        ['code' => '+27',  'flag' => '🇿🇦', 'name' => 'South Africa (+27)', 'short' => 'ZA'],
        ['code' => '+64',  'flag' => '🇳🇿', 'name' => 'New Zealand (+64)', 'short' => 'NZ'],
        ['code' => '+34',  'flag' => '🇪🇸', 'name' => 'Spain (+34)', 'short' => 'ES'],
        ['code' => '+31',  'flag' => '🇳🇱', 'name' => 'Netherlands (+31)', 'short' => 'NL'],
        ['code' => '+46',  'flag' => '🇸🇪', 'name' => 'Sweden (+46)', 'short' => 'SE'],
        ['code' => '+41',  'flag' => '🇨🇭', 'name' => 'Switzerland (+41)', 'short' => 'CH'],
        ['code' => '+47',  'flag' => '🇳🇴', 'name' => 'Norway (+47)', 'short' => 'NO'],
        ['code' => '+45',  'flag' => '🇩🇰', 'name' => 'Denmark (+45)', 'short' => 'DK'],
        ['code' => '+358', 'flag' => '🇫🇮', 'name' => 'Finland (+358)', 'short' => 'FI'],
        ['code' => '+353', 'flag' => '🇮🇪', 'name' => 'Ireland (+353)', 'short' => 'IE'],
        ['code' => '+351', 'flag' => '🇵🇹', 'name' => 'Portugal (+351)', 'short' => 'PT'],
        ['code' => '+30',  'flag' => '🇬🇷', 'name' => 'Greece (+30)', 'short' => 'GR'],
        ['code' => '+43',  'flag' => '🇦🇹', 'name' => 'Austria (+43)', 'short' => 'AT'],
        ['code' => '+32',  'flag' => '🇧🇪', 'name' => 'Belgium (+32)', 'short' => 'BE'],
        ['code' => '+55',  'flag' => '🇧🇷', 'name' => 'Brazil (+55)', 'short' => 'BR'],
        ['code' => '+52',  'flag' => '🇲🇽', 'name' => 'Mexico (+52)', 'short' => 'MX'],
        ['code' => '+86',  'flag' => '🇨🇳', 'name' => 'China (+86)', 'short' => 'CN'],
        ['code' => '+852', 'flag' => '🇭🇰', 'name' => 'Hong Kong (+852)', 'short' => 'HK'],
        ['code' => '+886', 'flag' => '🇹🇼', 'name' => 'Taiwan (+886)', 'short' => 'TW'],
        ['code' => '+63',  'flag' => '🇵🇭', 'name' => 'Philippines (+63)', 'short' => 'PH'],
        ['code' => '+84',  'flag' => '🇻🇳', 'name' => 'Vietnam (+84)', 'short' => 'VN'],
        ['code' => '+962', 'flag' => '🇯🇴', 'name' => 'Jordan (+962)', 'short' => 'JO'],
        ['code' => '+961', 'flag' => '🇱🇧', 'name' => 'Lebanon (+961)', 'short' => 'LB'],
        ['code' => '+964', 'flag' => '🇮🇶', 'name' => 'Iraq (+964)', 'short' => 'IQ'],
        ['code' => '+212', 'flag' => '🇲🇦', 'name' => 'Morocco (+212)', 'short' => 'MA'],
        ['code' => '+234', 'flag' => '🇳🇬', 'name' => 'Nigeria (+234)', 'short' => 'NG'],
        ['code' => '+254', 'flag' => '🇰🇪', 'name' => 'Kenya (+254)', 'short' => 'KE'],
        ['code' => '+7',   'flag' => '🇷🇺', 'name' => 'Russia (+7)', 'short' => 'RU'],
    ];
@endphp

@foreach($countryList as $c)
    <option value="{{ $c['code'] }}" {{ $selectedCode === $c['code'] ? 'selected' : '' }}>
        {{ $c['flag'] }} {{ $c['code'] }}
    </option>
@endforeach
