<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/AdminLayout.vue';
import KpiCard from '@/Components/Admin/KpiCard.vue';
import DateRangePicker from '@/Components/Admin/DateRangePicker.vue';
import ExportButton from '@/Components/Admin/ExportButton.vue';

interface BookMetrics {
    total_units_sold: number;
    total_revenue: number;
}

interface PaginatedBooks {
    data: Array<{
        book_id: number;
        units_sold: number;
        total_revenue: number;
        book?: {
            title: string;
            sku: string;
            isbn_13: string;
            cover_url: string;
            stock_quantity: number;
            category?: {
                name: string;
            };
            publisher?: {
                name: string;
            };
            authors?: Array<{
                pen_name: string;
            }>;
        };
    }>;
    links: Array<{
        url: string | null;
        label: string;
        active: boolean;
    }>;
}

const props = defineProps<{
    metrics: BookMetrics;
    books: PaginatedBooks;
    filters: {
        start_date: string;
        end_date: string;
    };
}>();
</script>

<template>
    <Head title="Top Books Analytics — BookVerse" />

    <AdminLayout>
        <template #header>
            Best Selling Books Analytics
        </template>

        <div class="p-6 sm:p-8 space-y-8 font-sans">
            <!-- Header Title & Action Bar -->
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-gradient-to-r from-indigo-500/10 via-purple-500/10 to-sky-500/10 dark:from-indigo-950/30 dark:via-purple-950/30 dark:to-sky-950/30 p-6 rounded-3xl border border-indigo-200/50 dark:border-indigo-900/30">
                <div class="space-y-1">
                    <h1 class="text-xl sm:text-2xl font-black font-heading text-slate-900 dark:text-white tracking-tight flex items-center gap-2.5">
                        <span class="w-9 h-9 rounded-2xl bg-indigo-600 text-white flex items-center justify-center text-lg shadow-md shadow-indigo-500/25">📚</span>
                        Best Selling Books Ranking
                    </h1>
                    <p class="text-xs text-slate-500 dark:text-zinc-400 font-mono">
                        Distribution volume, revenue contributions & stock status of top-performing catalog titles
                    </p>
                </div>

                <ExportButton type="books" :start-date="filters.start_date" :end-date="filters.end_date" />
            </div>

            <!-- Date Range Filter Toolbar -->
            <DateRangePicker :start-date="filters.start_date" :end-date="filters.end_date" />

            <!-- KPI Summary Grid -->
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-5 max-w-2xl">
                <KpiCard
                    title="Units Distributed"
                    :value="metrics.total_units_sold"
                    icon="📚"
                    variant="indigo"
                    subtitle="Total copies sold in range"
                />

                <KpiCard
                    title="Revenue Contribution"
                    :value="`৳${metrics.total_revenue.toLocaleString()}`"
                    icon="💰"
                    variant="emerald"
                    subtitle="Total revenue generated by items"
                />
            </div>

            <!-- Best Sellers Performance Table -->
            <div class="bg-white dark:bg-zinc-900 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-sm overflow-hidden">
                <div class="px-6 py-5 border-b border-slate-100 dark:border-zinc-800 flex items-center justify-between">
                    <h3 class="font-extrabold text-base text-slate-900 dark:text-zinc-100 font-heading flex items-center gap-2">
                        🏆 Book Sales Leaderboard
                    </h3>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full text-left text-xs border-collapse">
                        <thead>
                            <tr class="bg-slate-50/80 dark:bg-zinc-800/60 border-b border-slate-100 dark:border-zinc-800 text-slate-500 dark:text-zinc-400 font-extrabold uppercase font-mono">
                                <th class="px-6 py-3.5">Book Details</th>
                                <th class="px-6 py-3.5">Category & Publisher</th>
                                <th class="px-6 py-3.5">Units Sold</th>
                                <th class="px-6 py-3.5">Revenue</th>
                                <th class="px-6 py-3.5">Current Stock</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-slate-100 dark:divide-zinc-800 text-slate-700 dark:text-zinc-300">
                            <tr v-for="item in books.data" :key="item.book_id" class="hover:bg-slate-50/60 dark:hover:bg-zinc-800/40 transition">
                                <td class="px-6 py-4">
                                    <div class="flex items-center gap-3.5">
                                        <img
                                            :src="item.book?.cover_url || '/images/default_cover.jpg'"
                                            class="w-10 h-14 rounded-lg object-cover shadow-xs border border-slate-100 dark:border-zinc-800"
                                            alt="Cover"
                                        />
                                        <div>
                                            <span class="font-black text-slate-900 dark:text-zinc-100 block leading-tight mb-1">
                                                {{ item.book?.title ?? 'Deleted Book' }}
                                            </span>
                                            <span class="text-[10px] text-slate-400 dark:text-zinc-500 font-mono block">
                                                SKU: {{ item.book?.sku ?? 'N/A' }} | ISBN: {{ item.book?.isbn_13 ?? 'N/A' }}
                                            </span>
                                            <span class="text-[10px] font-semibold text-indigo-600 dark:text-indigo-400 block mt-0.5" v-if="item.book?.authors && item.book.authors.length">
                                                By: {{ item.book.authors.map(a => a.pen_name).join(', ') }}
                                            </span>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-6 py-4">
                                    <span class="font-semibold text-slate-800 dark:text-zinc-200 block">{{ item.book?.category?.name ?? 'Uncategorized' }}</span>
                                    <span class="text-[10px] text-slate-400 dark:text-zinc-500 font-mono block">{{ item.book?.publisher?.name ?? 'N/A' }}</span>
                                </td>
                                <td class="px-6 py-4">
                                    <span class="font-black text-slate-900 dark:text-zinc-100 text-sm font-mono">{{ item.units_sold }}</span>
                                </td>
                                <td class="px-6 py-4">
                                    <span class="font-black text-slate-900 dark:text-zinc-100 font-mono text-sm">৳{{ item.total_revenue }}</span>
                                </td>
                                <td class="px-6 py-4">
                                    <span
                                        class="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold font-mono"
                                        :class="(item.book?.stock_quantity ?? 0) > 5 ? 'bg-emerald-50 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800/40' : 'bg-rose-50 dark:bg-rose-950/50 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-800/40'"
                                    >
                                        {{ item.book?.stock_quantity ?? 0 }} in stock
                                    </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <!-- Pagination footer -->
                <div class="px-6 py-4 border-t border-slate-100 dark:border-zinc-800 flex items-center justify-between bg-slate-50/40 dark:bg-zinc-800/20">
                    <span class="text-xs text-slate-500 dark:text-zinc-400 font-medium">Page {{ books.data.length ? 1 : 0 }}</span>
                    <div class="flex items-center gap-1.5">
                        <template v-for="link in books.links">
                            <Link
                                v-if="link.url"
                                :href="link.url"
                                v-html="link.label"
                                class="px-3 py-1.5 rounded-xl border text-[11px] font-bold transition-all"
                                :class="link.active ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm' : 'bg-white dark:bg-zinc-800 hover:bg-slate-50 dark:hover:bg-zinc-700 text-slate-700 dark:text-zinc-200 border-slate-200 dark:border-zinc-700'"
                            />
                            <span
                                v-else
                                v-html="link.label"
                                class="px-3 py-1.5 rounded-xl border text-[11px] font-bold text-slate-300 dark:text-zinc-600 bg-slate-50 dark:bg-zinc-800/40 border-slate-200 dark:border-zinc-800 cursor-not-allowed"
                            />
                        </template>
                    </div>
                </div>
            </div>
        </div>
    </AdminLayout>
</template>
